/**
 * dsh-save-money — Host half (official plugin module, generated by
 * scripts/make-plugin.js from dist/host.js, built from src/host.ts).
 *
 * Deployment form: DeepSeek Harness official bundle / --patch mount (see
 * README "Install"). Behaviour is identical to the dynamic-plugin form:
 * time-window scheduling + goal freeze/resume + PauseRecord + llm/stream
 * request-level gate (event-driven suspension) + dynamic tools + HTTP
 * endpoints (/save-money/*) for the bundled Client half + config persistence.
 */

export const name = 'dsh-save-money'
export const inject = ['timer']

/**
 * dsh-save-money — Pure scheduling/time logic (single source of truth).
 *
 * All timezone conversion, window matching and validation helpers live here as
 * plain exported functions so they can be unit-tested (tests/core.test.js) and
 * are inlined into the Host plugin body at build time (scripts/build.js).
 * Nothing in this module touches Cordis, services, or the sandbox.
 */
/** Convert a Date to wall-clock components in the given IANA timezone. */
function wallClock(tz, date) {
    const f = new Intl.DateTimeFormat('en-US', {
        timeZone: tz, hour12: false,
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
    });
    const parts = {};
    for (const p of f.formatToParts(date))
        parts[p.type] = p.value;
    const y = Number(parts.year), mo = Number(parts.month), d = Number(parts.day);
    const weekday = new Date(Date.UTC(y, mo - 1, d)).getUTCDay();
    const minutes = Number(parts.hour) * 60 + Number(parts.minute);
    return { y, mo, d, weekday, minutes };
}
/** Parse "HH:mm" into minutes-of-day, or null when invalid. */
function parseHHMM(s) {
    const m = /^(\d{1,2}):(\d{2})$/.exec(String(s).trim());
    if (!m)
        return null;
    const h = Number(m[1]), mi = Number(m[2]);
    if (h > 23 || mi > 59)
        return null;
    return h * 60 + mi;
}
/** Sunday (0) → 7 so ISO weekday numbering is 1..7. */
function dowNum(wd) { return wd === 0 ? 7 : wd; }
/** True when the window is active at the given wall-clock time. */
function windowMatchesAt(w, wc) {
    if (w.days && w.days.length && !w.days.includes(dowNum(wc.weekday)))
        return false;
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p === null || r === null || p === r)
        return false;
    const m = wc.minutes;
    if (p < r)
        return m >= p && m < r;
    return m >= p || m < r;
}
/** Next pause offset (in days and minutes-of-day) for a window, or null. */
function nextPause(w, tz, wc) {
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p === null || r === null || p === r)
        return null;
    for (let off = 0; off <= 8; off++) {
        const d = new Date(Date.UTC(wc.y, wc.mo - 1, wc.d + off));
        const wd = dowNum(d.getUTCDay());
        if (w.days && w.days.length && !w.days.includes(wd))
            continue;
        if (off === 0) {
            if (p > wc.minutes)
                return { dayOffset: 0, minutes: p };
            continue;
        }
        return { dayOffset: off, minutes: p };
    }
    return null;
}
/**
 * Convert a wall-clock HH:mm on a given date to an epoch-ms UTC instant.
 * Robust for any real offset (incl. ±12/±13h like Pacific/Auckland): first
 * align the wall-clock DATE (full-day steps), then align the minutes within
 * that day — forward-only stepping would cross days for large offsets.
 */
function wallToUTC(tz, y, mo, d, hhmm) {
    let ms = Date.UTC(y, mo - 1, d, Math.floor(hhmm / 60), hhmm % 60);
    const targetDay = Date.UTC(y, mo - 1, d);
    for (let i = 0; i < 8; i++) {
        const w = wallClock(tz, new Date(ms));
        if (w.y === y && w.mo === mo && w.d === d && w.minutes === hhmm)
            return ms;
        const curDay = Date.UTC(w.y, w.mo - 1, w.d);
        const dayDiff = Math.round((curDay - targetDay) / 86400000);
        if (dayDiff !== 0) {
            ms -= dayDiff * 86400000;
            continue;
        }
        ms += (hhmm - w.minutes) * 60000;
    }
    return ms;
}
/** Format minutes-of-day as "HH:mm" (zero-padded). */
function formatHHMM(m) {
    const h = Math.floor(m / 60);
    const mi = m % 60;
    return String(h).padStart(2, '0') + ':' + String(mi).padStart(2, '0');
}
/**
 * Convert a wall-clock HH:mm from one IANA timezone to another, using the
 * given reference date (default: now) so real timezone rules apply
 * (daylight-saving aware). The result keeps the same absolute instant:
 * Beijing 08:58 on a summer day becomes London 01:58, on a winter day 00:58.
 */
function convertHHMM(tzFrom, tzTo, hhmm, ref) {
    const date = ref || new Date();
    const wc = wallClock(tzFrom, date);
    const ms = wallToUTC(tzFrom, wc.y, wc.mo, wc.d, hhmm);
    return wallClock(tzTo, new Date(ms)).minutes;
}
/**
 * UTC offset of a timezone at the given instant, in minutes (DST-aware).
 * Correct at minute precision: interpret the timezone's wall-clock minute as
 * if it were UTC, and subtract the real UTC instant that wall-clock minute
 * maps to. E.g. Asia/Shanghai -> 480, Europe/London -> 60 in summer / 0 in
 * winter, America/New_York -> -240 in summer / -300 in winter.
 */
function utcOffsetMinutes(tz, date) {
    const wc = wallClock(tz, date);
    const tzMs = wallToUTC(tz, wc.y, wc.mo, wc.d, wc.minutes);
    const utcMs = Date.UTC(wc.y, wc.mo - 1, wc.d, Math.floor(wc.minutes / 60), wc.minutes % 60);
    return Math.round((utcMs - tzMs) / 60000);
}
/** True when the string is a valid IANA timezone name. */
function isValidTz(tz) {
    try {
        new Intl.DateTimeFormat('en-US', { timeZone: tz });
        return true;
    }
    catch (e) {
        return false;
    }
}
/** Window as half-open minute ranges (handles midnight-crossing). */
function rangesOf(w) {
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p < r)
        return [[p, r]];
    return [[p, 1440], [0, r]];
}
function rangesIntersect(a, b) {
    for (const sa of a)
        for (const sb of b) {
            if (sa[0] < sb[1] && sb[0] < sa[1])
                return true;
        }
    return false;
}
function daysOverlap(a, b) {
    const da = (a.days && a.days.length) ? a.days : [1, 2, 3, 4, 5, 6, 7];
    const db = (b.days && b.days.length) ? b.days : [1, 2, 3, 4, 5, 6, 7];
    return da.some((d) => db.includes(d));
}
/**
 * Validate a windows array: shape, HH:mm syntax, pause != resume, IANA
 * timezone, days 1-7, and same-timezone overlap (incl. midnight-crossing and
 * weekday-intersection cases).
 */
function validateWindows(windows, defaultTz) {
    if (!Array.isArray(windows))
        return { ok: false, error: 'windows must be an array' };
    for (const w of windows) {
        if (!w || typeof w !== 'object')
            return { ok: false, error: 'window must be an object' };
        if (parseHHMM(w.pauseAt) === null || parseHHMM(w.resumeAt) === null) {
            return { ok: false, error: 'bad HH:mm in window ' + JSON.stringify(w) };
        }
        if (parseHHMM(w.pauseAt) === parseHHMM(w.resumeAt)) {
            return { ok: false, error: 'pauseAt == resumeAt in window ' + JSON.stringify(w) };
        }
        if (w.timezone !== undefined && !isValidTz(w.timezone)) {
            return { ok: false, error: 'invalid IANA timezone: ' + w.timezone };
        }
        if (w.days !== undefined && (!Array.isArray(w.days) || !w.days.every((d) => Number.isInteger(d) && d >= 1 && d <= 7))) {
            return { ok: false, error: 'days must be array of 1-7' };
        }
    }
    for (let i = 0; i < windows.length; i++) {
        for (let j = i + 1; j < windows.length; j++) {
            const a = windows[i], b = windows[j];
            const aTz = a.timezone || defaultTz, bTz = b.timezone || defaultTz;
            if (aTz !== bTz)
                continue;
            if (!daysOverlap(a, b))
                continue;
            if (rangesIntersect(rangesOf(a), rangesOf(b))) {
                return { ok: false, error: 'overlapping windows: ' + JSON.stringify(a) + ' vs ' + JSON.stringify(b) };
            }
        }
    }
    return { ok: true };
}

export function apply(ctx) {
        const DEFAULTS = {
            enabled: false,
            timezone: 'Asia/Shanghai',
            warnMinutes: 5,
            windows: [],
            reconcileOnStart: true,
            lang: 'auto',
        };
        let cfg = { ...DEFAULTS, windows: [] };
        let pauseRecord = null;
        // "End this save mode" state — one-shot, in-memory only (never persisted):
        // applies to the exact window it was invoked for (matched by key), expires
        // at that window's resumeAt, and leaves the persistent `enabled` flag
        // untouched. The next window (today or later) is unaffected.
        let endWindowUntil = 0;
        let endWindowKey = null;
        let lastStateKey = 'NORMAL';
        let configLoaded = false;
        let configPath = '';
        const unwrap = (args) => (args && typeof args === 'object' && args.arguments && typeof args.arguments === 'object' ? args.arguments : args);
        // Config persistence to the workspace file (survives browser refresh /
        // plugin re-activation). The workspace root is fetched at runtime from the
        // sandboxPolicy service; when unavailable, fs.resolve falls back to its
        // default cwd (the workspace). No machine path is ever hard-coded.
        const CONFIG_FILE = 'save-money.config.json';
        const sandboxPolicy = ctx.get('sandboxPolicy');
        const sessionsSvc = ctx.get('sessions');
        const defaultWorkspaceRoot = (sandboxPolicy && typeof sandboxPolicy.workspaceRoot === 'string' && sandboxPolicy.workspaceRoot.length > 0)
            ? sandboxPolicy.workspaceRoot
            : '';
        // sandboxPolicy.workspaceRoot is the process cwd (the DSH install dir), not
        // the session workspace. The plugin config belongs to the save-money
        // workspace, so prefer a session whose cwd points at this repo (matched by
        // directory basename only — no machine path is hard-coded).
        const sessionCwdOf = (s) => {
            const c = s && (s.meta && s.meta.cwd || s.header && s.header.cwd || s.cwd);
            return typeof c === 'string' ? c : '';
        };
        const resolveWorkspaceRoot = () => {
            // Prefer the CALLING session (agents.currentInitiator) so the config
            // follows the session that actually uses the plugin (tool/RPC calls
            // resolve to the workspace the user is working in, not an older
            // checkout that happens to be listed first).
            try {
                const agentsSvc = ctx.get('agents');
                const init = agentsSvc && typeof agentsSvc.currentInitiator === 'function'
                    ? agentsSvc.currentInitiator()
                    : undefined;
                if (init && sessionsSvc && typeof sessionsSvc.get === 'function') {
                    const s = sessionsSvc.get(init.id);
                    const c = sessionCwdOf(s || init).replace(/[\\/]+$/, '');
                    if (/dsh-save-money$/i.test(c))
                        return c;
                }
            }
            catch (e) { /* keep the default */ }
            let ws = defaultWorkspaceRoot;
            if (sessionsSvc && typeof sessionsSvc.list === 'function') {
                try {
                    let matched = '';
                    // sessions.list() returns creation order; keep the LAST match so
                    // the newest (current) workspace wins when several checkouts
                    // exist, while a single checkout still resolves trivially.
                    for (const s of sessionsSvc.list()) {
                        const c = sessionCwdOf(s).replace(/[\\/]+$/, '');
                        if (/dsh-save-money$/i.test(c))
                            matched = c;
                    }
                    if (matched)
                        ws = matched;
                }
                catch (e) { /* keep the default */ }
            }
            return ws;
        };
        const fsSvc = ctx.get('fs');
        const windowKey = (w, tz) => w.pauseAt + '|' + w.resumeAt + '|' + (w.timezone || tz);
        const persistConfig = async () => {
            if (!fsSvc)
                return;
            try {
                const workspaceRoot = resolveWorkspaceRoot();
                const resolveOpts = workspaceRoot ? { cwd: workspaceRoot } : undefined;
                const writePolicy = workspaceRoot ? { mode: 'workspace-write', workspaceRoot } : undefined;
                const target = await fsSvc.resolve(CONFIG_FILE, resolveOpts);
                configPath = fsSvc.processPath ? String(fsSvc.processPath(target)) : String(target && (target.path || target.filePath || ''));
                await fsSvc.writeText(target, JSON.stringify(snapshot(), null, 2), undefined, undefined, writePolicy);
                console.log('[save-money] config persisted to ' + (workspaceRoot ? workspaceRoot + '\\' + CONFIG_FILE : CONFIG_FILE));
            }
            catch (e) {
                console.error('[save-money] persist failed: ' + String((e && e.message) || e));
            }
        };
        const loadConfig = async () => {
            if (!fsSvc)
                return;
            try {
                const workspaceRoot = resolveWorkspaceRoot();
                const resolveOpts = workspaceRoot ? { cwd: workspaceRoot } : undefined;
                const target = await fsSvc.resolve(CONFIG_FILE, resolveOpts);
                configPath = fsSvc.processPath ? String(fsSvc.processPath(target)) : String(target && (target.path || target.filePath || ''));
                const text = await fsSvc.readText(target);
                const data = JSON.parse(text);
                configLoaded = true;
                const next = { ...cfg };
                if (typeof data.enabled === 'boolean')
                    next.enabled = data.enabled;
                if (typeof data.timezone === 'string' && isValidTz(data.timezone))
                    next.timezone = data.timezone;
                if (typeof data.warnMinutes === 'number' && data.warnMinutes >= 0)
                    next.warnMinutes = data.warnMinutes;
                if (typeof data.reconcileOnStart === 'boolean')
                    next.reconcileOnStart = data.reconcileOnStart;
                if (data.lang === 'auto' || data.lang === 'zh' || data.lang === 'zh-TW' || data.lang === 'en' ||
                    data.lang === 'de' || data.lang === 'fr' || data.lang === 'es' || data.lang === 'it' ||
                    data.lang === 'pt' || data.lang === 'ja' || data.lang === 'ko')
                    next.lang = data.lang;
                if (Array.isArray(data.windows)) {
                    const v = validateWindows(data.windows, next.timezone);
                    if (v.ok)
                        next.windows = data.windows.map((w) => ({ ...w }));
                }
                cfg = next;
                console.log('[save-money] config loaded from ' + (workspaceRoot ? workspaceRoot + '\\' + CONFIG_FILE : CONFIG_FILE));
            }
            catch (e) {
                console.log('[save-money] no config file (fresh start): ' + String((e && e.message) || e));
            }
        };
        // ---------- Config ----------
        // Pure helpers (wallClock / parseHHMM / windowMatchesAt / nextPause /
        // wallToUTC / isValidTz / validateWindows) live in src/core.ts and are
        // inlined into this body at build time; see the declarations above.
        function applyConfig(patch) {
            const next = { ...cfg, ...patch };
            if (next.windows === undefined)
                next.windows = [];
            const v = validateWindows(next.windows, next.timezone);
            if (!v.ok)
                return { ok: false, error: v.error };
            if (next.timezone !== undefined && !isValidTz(next.timezone)) {
                return { ok: false, error: 'invalid IANA timezone: ' + next.timezone };
            }
            if (next.warnMinutes !== undefined && (!Number.isFinite(next.warnMinutes) || next.warnMinutes < 0)) {
                return { ok: false, error: 'warnMinutes must be >= 0' };
            }
            const LANGS = ['auto', 'zh', 'zh-TW', 'en', 'de', 'fr', 'es', 'it', 'pt', 'ja', 'ko'];
            if (next.lang !== undefined && !LANGS.includes(next.lang)) {
                return { ok: false, error: 'lang must be one of auto/zh/zh-TW/en/de/fr/es/it/pt/ja/ko' };
            }
            // Re-activation resets the one-shot "end this save mode" state: when
            // `enabled` goes false -> true, clear endWindowUntil/endWindowKey so
            // every window takes effect again. The user gets a deterministic way to
            // re-arm saving money (e.g. after skipping a window during a test) by
            // toggling the Enable switch off and on.
            if (patch && patch.enabled === true && !cfg.enabled) {
                endWindowUntil = 0;
                endWindowKey = null;
                console.log('[save-money] re-enabled: end-this-save-mode state reset');
            }
            cfg = next;
            // Wake waiters only when the gate is actually open (unconditional wake
            // released suspended requests inside the window — observed as "still
            // thinking after pause" caused by the tick releasing every 60s).
            if (!gateClosedAt(new Date()))
                wakeGateWaiters();
            void persistConfig(); // persist on every config change
            return { ok: true, config: snapshot() };
        }
        function snapshot() {
            return {
                enabled: cfg.enabled,
                timezone: cfg.timezone,
                warnMinutes: cfg.warnMinutes,
                reconcileOnStart: cfg.reconcileOnStart,
                lang: cfg.lang,
                windows: cfg.windows.map((w) => ({ ...w })),
            };
        }
        // ---------- Busy detection / freeze / resume ----------
        function collectTasks() {
            const agents = ctx.get('agents');
            const goals = ctx.get('goals');
            if (!agents || !goals)
                return { ok: false, tasks: [], reason: 'agents/goals services unavailable' };
            const tasks = [];
            for (const agent of agents.list()) {
                let gv = undefined;
                try {
                    gv = goals.get(agent);
                }
                catch (e) {
                    gv = undefined;
                }
                if (gv && (gv.phase === 'active' || (pauseRecord && pauseRecord.paused && pauseRecord.paused.some((p) => p.sessionId === agent.id)))) {
                    tasks.push({ agent, sessionId: agent.id, goalId: gv.id, revision: gv.revision, phase: gv.phase });
                }
            }
            return { ok: true, tasks };
        }
        function freeze(window) {
            const col = collectTasks();
            if (!col.ok) {
                console.error('[save-money] freeze skipped:', col.reason);
                return { frozen: 0, record: null };
            }
            const freezeTargets = col.tasks.filter((t) => t.phase === 'active');
            if (freezeTargets.length === 0) {
                console.log('[save-money] pauseAt reached but no active tasks; not pausing');
                return { frozen: 0, record: null };
            }
            const goals = ctx.get('goals');
            const paused = [];
            for (const t of freezeTargets) {
                try {
                    goals.pause(t.agent, { id: t.goalId, revision: t.revision });
                    paused.push({ sessionId: t.sessionId, goalId: t.goalId, revision: t.revision, pausedAt: Date.now() });
                }
                catch (e) {
                    console.error('[save-money] goals.pause failed for ' + t.sessionId + ': ' + String((e && e.message) || e));
                }
            }
            pauseRecord = {
                pausedBySaveMoney: true,
                at: new Date().toISOString(),
                window: window ? { pauseAt: window.pauseAt, resumeAt: window.resumeAt, timezone: window.timezone || cfg.timezone } : null,
                paused,
                cascaded: true,
            };
            console.log('[save-money] FROZEN ' + paused.length + ' goal(s), record written');
            return { frozen: paused.length, record: pauseRecord };
        }
        function unfreeze() {
            if (!pauseRecord)
                return { resumed: 0, record: null };
            const agents = ctx.get('agents');
            const goals = ctx.get('goals');
            const remaining = [];
            let resumed = 0;
            const targets = pauseRecord.paused || [];
            for (const p of targets) {
                const agent = agents && agents.get(p.sessionId);
                if (!agent)
                    continue;
                try {
                    const gv = goals.get(agent);
                    if (gv && gv.phase === 'paused') {
                        goals.resume(agent, { id: gv.id, revision: gv.revision });
                        resumed++;
                    }
                    else if (gv && gv.phase === 'active') {
                        resumed++;
                    }
                }
                catch (e) {
                    console.error('[save-money] goals.resume failed for ' + p.sessionId + ': ' + String((e && e.message) || e));
                    remaining.push(p);
                }
            }
            pauseRecord = remaining.length > 0 ? { ...pauseRecord, paused: remaining } : null;
            console.log('[save-money] RESUMED ' + resumed + ' goal(s)' + (remaining.length > 0 ? ', ' + remaining.length + ' still pending' : ', record cleared'));
            return { resumed, record: pauseRecord };
        }
        ctx.effect(() => {
            return () => {
                if (pauseRecord && pauseRecord.paused && pauseRecord.paused.length > 0) {
                    console.log('[save-money] plugin unloading: restoring paused goals');
                    unfreeze();
                }
            };
        });
        // ---------- State computation ----------
        function computeRawState(now) {
            if (!cfg.enabled)
                return { name: 'NORMAL', reason: 'disabled' };
            for (const w of cfg.windows) {
                const tz = w.timezone || cfg.timezone;
                if (windowMatchesAt(w, wallClock(tz, now))) {
                    // "End this save mode" only affects the exact window it was applied
                    // to — a stale endWindowUntil must not suppress later windows.
                    if (endWindowUntil > now.getTime() && endWindowKey === windowKey(w, tz))
                        return { name: 'NORMAL', reason: 'ended', window: w };
                    return { name: 'PAUSED', window: w };
                }
            }
            let nearest = null;
            for (const w of cfg.windows) {
                const tz = w.timezone || cfg.timezone;
                const wc = wallClock(tz, now);
                const np = nextPause(w, tz, wc);
                if (!np)
                    continue;
                const delta = np.dayOffset * 1440 + np.minutes - wc.minutes;
                if (nearest === null || delta < nearest.delta)
                    nearest = { delta, window: w };
            }
            if (nearest !== null && nearest.delta > 0 && nearest.delta <= cfg.warnMinutes) {
                // The upcoming window may already be ended via "end this save mode"
                // (clicked while WARN) — do not keep showing "pause soon", suppress it
                // until the window's own resumeAt.
                if (endWindowUntil > now.getTime() && endWindowKey === windowKey(nearest.window, nearest.window.timezone || cfg.timezone)) {
                    return { name: 'NORMAL', reason: 'ended', window: nearest.window };
                }
                return { name: 'WARN', window: nearest.window, minutesToPause: nearest.delta };
            }
            return { name: 'NORMAL', reason: 'no-window' };
        }
        function onTick(now) {
            const raw = computeRawState(now);
            let st = raw;
            if (raw.name === 'PAUSED') {
                if (!pauseRecord) {
                    const col = collectTasks();
                    if (!col.ok || col.tasks.length === 0)
                        st = { name: 'NORMAL', reason: 'no-task' };
                }
            }
            const key = st.name + (st.window ? ':' + st.window.pauseAt : '');
            if (key !== lastStateKey) {
                const prevName = lastStateKey.split(':')[0];
                lastStateKey = key;
                if (st.name === 'PAUSED' && prevName !== 'PAUSED') {
                    freeze(st.window);
                }
                else if (st.name !== 'PAUSED' && prevName === 'PAUSED') {
                    unfreeze();
                }
                console.log('[save-money] state -> ' + key);
            }
        }
        // ---------- Request-level gate (event-driven suspension; never throws,
        //            zero timer dependencies) ----------
        // Inside a pause window every streaming model call is intercepted (llm/stream
        // is the mandatory waterfall every call goes through). The gate uses the
        // same "inside window and not ignored" check as the state machine, and does
        // NOT depend on the freeze record: even when no active goal is frozen,
        // manual-conversation model requests are still suspended — that is
        // the saving-money semantics.
        // Implementation notes:
        //  - Cordis 3 registration API is ctx.on only; llm.stream dispatches via
        //    ctx.waterfall, and listeners must synchronously return an AsyncIterable
        //    (the caller for-await's it; an async listener would break the return
        //    type). So we return a WRAPPER stream: iteration waits for the gate to
        //    open first, then calls next() to get the real stream — options pass
        //    through untouched, routing/retry/validation are unaffected (we are
        //    registered at the chain tail; the suspend happens before the actual
        //    adapterStream).
        //  - The sandbox has no Node timer globals (setTimeout throws and fails the
        //    turn as "this run failed"); ctx.timer.timeout is a fiber effect and can
        //    still throw when registered inside an agent-turn fiber context. So
        //    waiting is EVENT-DRIVEN: suspending = registering the resolve into
        //    gateWaiters, woken by: ① the 60s tick (registered in the plugin apply
        //    context, runs reliably); ② applyConfig (disable / window change);
        //    ③ endWindowHandler (end-window); ④ plugin unload (fail-open); ⑤ request
        //    signal abort. No timers / fiber-effect calls → cannot throw, cannot
        //    interrupt a turn.
        let gateDisposed = false;
        let gateWaiters = [];
        const wakeGateWaiters = () => {
            const waiters = gateWaiters;
            gateWaiters = [];
            for (const resolve of waiters)
                resolve();
        };
        const gateClosedAt = (now) => {
            if (!cfg.enabled)
                return false;
            // The gate follows the state machine exactly: computeRawState already
            // exempts the ended window (endWindowKey match + endWindowUntil), so a
            // different window (e.g. cross-timezone overlap) stays gated.
            const st = computeRawState(now);
            return st.name === 'PAUSED';
        };
        const gateInstalled = typeof ctx.on === 'function';
        if (typeof ctx.on === 'function') {
            ctx.effect(() => {
                const dispose = ctx.on('llm/stream', (options, next) => {
                    if (!gateClosedAt(new Date()))
                        return next();
                    const waitForOpen = () => new Promise((resolve) => {
                        const ready = () => gateDisposed || !gateClosedAt(new Date())
                            || !!(options && options.signal && options.signal.aborted);
                        // On wake, resolve with next()'s result (the real stream); if next()
                        // throws, the executor throws → promise rejects.
                        if (ready())
                            return resolve(next());
                        const waiter = () => resolve(next());
                        gateWaiters.push(waiter);
                        if (options && options.signal && typeof options.signal.addEventListener === 'function') {
                            options.signal.addEventListener('abort', () => {
                                const i = gateWaiters.indexOf(waiter);
                                if (i >= 0)
                                    gateWaiters.splice(i, 1);
                                resolve(next());
                            }, { once: true });
                        }
                    });
                    // Wrapper stream: iteration waits only when the gate is closed; once
                    // open → next() → the real request proceeds as usual.
                    let inner = null;
                    const getInner = () => (inner !== null ? Promise.resolve(inner) : waitForOpen().then((s) => { inner = s; return inner; }));
                    return {
                        [Symbol.asyncIterator]() {
                            let it = null;
                            return {
                                next() {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.next();
                                    });
                                },
                                return(value) {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.return ? it.return(value) : { done: true, value };
                                    });
                                },
                                throw(e) {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.throw ? it.throw(e) : { done: true, value: e };
                                    });
                                },
                            };
                        },
                    };
                }, { global: true });
                return () => { gateDisposed = true; wakeGateWaiters(); dispose(); };
            });
        }
        else {
            console.error('[save-money] ctx.on unavailable; llm/stream gate not installed');
        }
        // ---------- Startup reconciliation ----------
        function reconcile() {
            const col = collectTasks();
            if (!col.ok)
                return { restored: 0, reason: col.reason };
            const goals = ctx.get('goals');
            const agents = ctx.get('agents');
            let restored = 0;
            for (const agent of agents.list()) {
                let gv = undefined;
                try {
                    gv = goals.get(agent);
                }
                catch (e) {
                    gv = undefined;
                }
                if (gv && gv.phase === 'paused') {
                    try {
                        goals.resume(agent, { id: gv.id, revision: gv.revision });
                        restored++;
                        console.log('[save-money] reconcile: restored paused goal of ' + agent.id);
                    }
                    catch (e) {
                        console.error('[save-money] reconcile resume failed for ' + agent.id + ': ' + String((e && e.message) || e));
                    }
                }
            }
            return { restored };
        }
        ctx.timer.timeout(() => {
            // Load the persisted config first, then run startup reconciliation
            void loadConfig().then(() => {
                if (cfg.reconcileOnStart) {
                    const r = reconcile();
                    if (r.restored > 0)
                        console.log('[save-money] startup reconcile restored ' + r.restored + ' goal(s)');
                }
            });
        }, 100);
        // ---------- Tick ----------
        ctx.timer.interval(() => {
            // Fallback release: whenever the gate is open (window ended / disabled /
            // end-window active) wake the waiters — this MUST run before the enabled
            // check, so disabling also releases waiters and suspended requests never
            // hang forever.
            if (!gateClosedAt(new Date()))
                wakeGateWaiters();
            if (!cfg.enabled)
                return;
            onTick(new Date());
        }, 60000);
        // ---------- Status ----------
        function status(now) {
            const st = computeRawState(now);
            const col = collectTasks();
            const out = {
                enabled: cfg.enabled,
                state: st.name,
                reason: st.reason || null,
                gate: gateClosedAt(now) ? 'closed' : 'open',
                gateInstalled,
                // Diagnostics (runtime workspace resolution) — helps verify where the
                // config file is loaded from / persisted to.
                workspaceRoot: resolveWorkspaceRoot(),
                configLoaded,
                configPath,
                nowUTC: now.toISOString(),
                nowLocal: String(now),
                busy: col.ok ? (col.tasks.length > 0) : null,
                activeGoals: col.ok ? col.tasks.filter((t) => t.phase === 'active').length : null,
            };
            if (st.window) {
                const tz = st.window.timezone || cfg.timezone;
                const wc = wallClock(tz, now);
                const pUTC = wallToUTC(tz, wc.y, wc.mo, wc.d, parseHHMM(st.window.pauseAt));
                const rUTC = wallToUTC(tz, wc.y, wc.mo, wc.d, parseHHMM(st.window.resumeAt));
                out.window = {
                    pauseAt: st.window.pauseAt,
                    resumeAt: st.window.resumeAt,
                    timezone: tz,
                    pauseUTC: new Date(pUTC).toISOString(),
                    resumeUTC: new Date(rUTC).toISOString(),
                };
            }
            if (st.name === 'WARN')
                out.minutesToPause = st.minutesToPause;
            if (endWindowUntil > now.getTime())
                out.endWindowUntil = new Date(endWindowUntil).toISOString();
            out.pauseRecord = pauseRecord ? {
                at: pauseRecord.at,
                window: pauseRecord.window,
                pausedCount: (pauseRecord.paused || []).length,
                paused: (pauseRecord.paused || []).map((p) => ({ sessionId: p.sessionId, goalId: p.goalId })),
            } : null;
            out.config = snapshot();
            return out;
        }
        // ---- Host RPC (dynamic-plugin form: registered on the harness sandbox)
        // ---- + HTTP endpoints (official bundle form: the bundled Client half
        //      talks to the same-origin webServer; the dynamic Client half keeps
        //      using the harness RPC below). Both are registered unconditionally
        //      so a single Host body serves every deployment form.
        const harnessApi = typeof harness !== 'undefined' ? harness : null;
        if (harnessApi) {
            ctx.effect(() => harnessApi.handle('save-money/status', async () => status(new Date())));
            ctx.effect(() => harnessApi.handle('save-money/configure', async (args) => applyConfig(unwrap(args) || {})));
        }
        const webServer = ctx.get('webServer');
        // The plugin row only injects timer, so in the official bundle form apply()
        // can run BEFORE the webServer service is registered. Register the HTTP
        // endpoints via Cordis' inject() dependency waiting — it runs the callback
        // as soon as webServer is available (immediately when already present), so
        // the bundled Client half never sees 404s (e.g. the Enable checkbox would
        // silently fail to configure). The disposer returned by webServer.register
        // is owned by the injected sub-context.
        const registerHttpEndpoints = (ws) => {
            if (!ws || typeof ws.register !== 'function')
                return;
            const sendJson = (res, code, obj) => {
                res.writeHead(code, { 'content-type': 'application/json; charset=utf-8' });
                res.end(JSON.stringify(obj));
            };
            return ws.register({
                kind: 'prefix',
                path: '/save-money',
                handler: async (req, res) => {
                    try {
                        const rawPath = String(req.url || '/').split('?')[0];
                        const path = rawPath.length > 1 ? rawPath.replace(/\/+$/, '') : rawPath;
                        if (path === '/save-money/status') {
                            sendJson(res, 200, status(new Date()));
                            return;
                        }
                        if (req.method === 'POST' && path === '/save-money/configure') {
                            let raw = '';
                            for await (const chunk of req)
                                raw += chunk;
                            let patch = {};
                            try {
                                patch = JSON.parse(raw || '{}');
                            }
                            catch (e) {
                                patch = {};
                            }
                            sendJson(res, 200, applyConfig(patch));
                            return;
                        }
                        if (req.method === 'POST' && path === '/save-money/end-window') {
                            for await (const _ of req) { /* drain */ }
                            sendJson(res, 200, await endWindowHandler());
                            return;
                        }
                        sendJson(res, 404, { ok: false, message: 'not found: ' + path });
                    }
                    catch (e) {
                        sendJson(res, 500, { ok: false, message: String((e && e.message) || e) });
                    }
                },
            });
        };
        if (webServer && typeof webServer.register === 'function') {
            ctx.effect(() => registerHttpEndpoints(webServer));
        }
        else if (typeof ctx.inject === 'function') {
            ctx.inject(['webServer'], (sub) => {
                sub.effect(() => registerHttpEndpoints(sub.get('webServer')));
            });
        }
        // UTC instant of a window's resumeAt (handles midnight-crossing windows).
        const endWindowUntilUTC = (w, tz, baseWc, dayOffset) => {
            const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
            const off = dayOffset + (r < p ? 1 : 0);
            const base = new Date(Date.UTC(baseWc.y, baseWc.mo - 1, baseWc.d + off));
            return wallToUTC(tz, base.getUTCFullYear(), base.getUTCMonth() + 1, base.getUTCDate(), r);
        };
        // "End this save mode" — one-shot, current window only:
        //  - paused: immediately resumes frozen goals and clears the record
        //  - pause upcoming (WARN): cancels the upcoming pause
        //  - no active window: nothing happens (never touches later windows)
        // The window is skipped until its resumeAt; the next window (today or
        // later) still takes effect; the persistent `enabled` flag is untouched.
        const endWindowHandler = async () => {
            const now = new Date();
            const raw = computeRawState(now);
            if (!raw.window) {
                console.log('[save-money] end-window: no active window');
                return { ok: false, message: 'no active pause window to end', ...status(now) };
            }
            const tz = raw.window.timezone || cfg.timezone;
            const wc = wallClock(tz, now);
            endWindowUntil = endWindowUntilUTC(raw.window, tz, wc, 0);
            endWindowKey = windowKey(raw.window, tz);
            if (lastStateKey.split(':')[0] === 'PAUSED') {
                lastStateKey = 'NORMAL';
                unfreeze();
            }
            wakeGateWaiters(); // the gate is now open (endWindowUntil), release immediately
            console.log('[save-money] ended save mode for this window until ' + new Date(endWindowUntil).toISOString());
            return status(new Date());
        };
        if (harnessApi) {
            ctx.effect(() => harnessApi.handle('save-money/end-window', async () => endWindowHandler()));
        }
        // ---- Dynamic tools ----
        // Registered through harness in the dynamic-plugin sandbox; through the
        // ctx.tools service in the official module (plugin/index.js) form.
        const TOOL_DEFS = [
            {
                name: 'save_money_status',
                description: 'Query the save-money plugin state: enabled, gate state (NORMAL/WARN/PAUSED), busy detection, current window with UTC projection, PauseRecord summary, and full config.',
                parameters: { type: 'object', properties: {} },
                execute: async () => status(new Date()),
            },
            {
                name: 'save_money_configure',
                description: 'Set the save-money plugin configuration. Partial patch: enabled (bool), timezone (IANA name), warnMinutes (number), reconcileOnStart (bool), lang (auto/zh/zh-TW/en/de/fr/es/it/pt/ja/ko), windows (array of {pauseAt, resumeAt, days?, timezone?}, HH:mm wall-clock in the window timezone). Validates, stores in memory, and persists to the workspace config file. Returns the applied config.',
                parameters: {
                    type: 'object',
                    properties: {
                        enabled: { type: 'boolean' },
                        timezone: { type: 'string' },
                        warnMinutes: { type: 'number' },
                        reconcileOnStart: { type: 'boolean' },
                        lang: { type: 'string' },
                        windows: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    pauseAt: { type: 'string' },
                                    resumeAt: { type: 'string' },
                                    days: { type: 'array', items: { type: 'number' } },
                                    timezone: { type: 'string' },
                                },
                            },
                        },
                    },
                },
                execute: async (args) => applyConfig(unwrap(args) || {}),
            },
            {
                name: 'save_money_end_window',
                description: 'End save mode for the currently active pause window only (one-shot, in-memory, not persisted): if paused, immediately resumes frozen goals and releases the request gate; if a pause is upcoming, cancels it. The window is skipped until its resumeAt. The next window (today or later) still takes effect; the persistent enabled flag is untouched. Returns the new status.',
                parameters: { type: 'object', properties: {} },
                execute: async () => endWindowHandler(),
            },
            {
                name: 'save_money_debug_tick',
                description: 'Development tool: run one state-machine transition manually (as if a tick fired now). Returns the new status. Useful to verify freeze/resume without waiting for the timer.',
                parameters: { type: 'object', properties: {} },
                execute: async () => {
                    onTick(new Date());
                    return status(new Date());
                },
            },
        ];
        for (const def of TOOL_DEFS) {
            const tool = {
                ...def,
                output: {
                    schema: { type: 'object', properties: {}, additionalProperties: true },
                    render: (_args, result) => [{ type: 'text', text: JSON.stringify(result) }],
                },
            };
            if (harnessApi) {
                ctx.effect(() => harnessApi.registerTool(ctx, harnessApi.defineTool(tool)));
            }
            else {
                const tools = ctx.get('tools');
                if (tools && typeof tools.register === 'function')
                    ctx.effect(() => tools.register(tool));
            }
        }
    }
