/**
 * dsh-save-money — Host half (official plugin module, generated by
 * scripts/make-plugin.js from dist/host.js, built from src/host.ts).
 *
 * Deployment form: DeepSeek Harness official bundle / --patch mount (see
 * README "Install"). Behaviour is identical to the dynamic-plugin form:
 * time-window scheduling + goal freeze/resume + PauseRecord + llm/stream
 * request-level gate (event-driven suspension) + dynamic tools + HTTP
 * endpoints (/save-money/*) for the bundled Client half + config persistence.
 */

export const name = 'dsh-save-money'
export const inject = ['timer']

/**
 * dsh-save-money — Pure scheduling/time logic (single source of truth).
 *
 * All timezone conversion, window matching and validation helpers live here as
 * plain exported functions so they can be unit-tested (tests/core.test.js) and
 * are inlined into the Host plugin body at build time (scripts/build.js).
 * Nothing in this module touches Cordis, services, or the sandbox.
 */
/** Convert a Date to wall-clock components in the given IANA timezone. */
function wallClock(tz, date) {
    const f = new Intl.DateTimeFormat('en-US', {
        timeZone: tz, hour12: false,
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit', second: '2-digit',
    });
    const parts = {};
    for (const p of f.formatToParts(date))
        parts[p.type] = p.value;
    const y = Number(parts.year), mo = Number(parts.month), d = Number(parts.day);
    const weekday = new Date(Date.UTC(y, mo - 1, d)).getUTCDay();
    const minutes = Number(parts.hour) * 60 + Number(parts.minute);
    return { y, mo, d, weekday, minutes };
}
/** Parse "HH:mm" into minutes-of-day, or null when invalid. */
function parseHHMM(s) {
    const m = /^(\d{1,2}):(\d{2})$/.exec(String(s).trim());
    if (!m)
        return null;
    const h = Number(m[1]), mi = Number(m[2]);
    if (h > 23 || mi > 59)
        return null;
    return h * 60 + mi;
}
/** Sunday (0) → 7 so ISO weekday numbering is 1..7. */
function dowNum(wd) { return wd === 0 ? 7 : wd; }
/** True when the window is active at the given wall-clock time. */
function windowMatchesAt(w, wc) {
    if (w.days && w.days.length && !w.days.includes(dowNum(wc.weekday)))
        return false;
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p === null || r === null || p === r)
        return false;
    const m = wc.minutes;
    if (p < r)
        return m >= p && m < r;
    return m >= p || m < r;
}
/** Next pause offset (in days and minutes-of-day) for a window, or null. */
function nextPause(w, tz, wc) {
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p === null || r === null || p === r)
        return null;
    for (let off = 0; off <= 8; off++) {
        const d = new Date(Date.UTC(wc.y, wc.mo - 1, wc.d + off));
        const wd = dowNum(d.getUTCDay());
        if (w.days && w.days.length && !w.days.includes(wd))
            continue;
        if (off === 0) {
            if (p > wc.minutes)
                return { dayOffset: 0, minutes: p };
            continue;
        }
        return { dayOffset: off, minutes: p };
    }
    return null;
}
/**
 * Convert a wall-clock HH:mm on a given date to an epoch-ms UTC instant.
 * Robust for any real offset (incl. ±12/±13h like Pacific/Auckland): first
 * align the wall-clock DATE (full-day steps), then align the minutes within
 * that day — forward-only stepping would cross days for large offsets.
 */
function wallToUTC(tz, y, mo, d, hhmm) {
    let ms = Date.UTC(y, mo - 1, d, Math.floor(hhmm / 60), hhmm % 60);
    const targetDay = Date.UTC(y, mo - 1, d);
    for (let i = 0; i < 8; i++) {
        const w = wallClock(tz, new Date(ms));
        if (w.y === y && w.mo === mo && w.d === d && w.minutes === hhmm)
            return ms;
        const curDay = Date.UTC(w.y, w.mo - 1, w.d);
        const dayDiff = Math.round((curDay - targetDay) / 86400000);
        if (dayDiff !== 0) {
            ms -= dayDiff * 86400000;
            continue;
        }
        ms += (hhmm - w.minutes) * 60000;
    }
    return ms;
}
/** Format minutes-of-day as "HH:mm" (zero-padded). */
function formatHHMM(m) {
    const h = Math.floor(m / 60);
    const mi = m % 60;
    return String(h).padStart(2, '0') + ':' + String(mi).padStart(2, '0');
}
/**
 * Convert a wall-clock HH:mm from one IANA timezone to another, using the
 * given reference date (default: now) so real timezone rules apply
 * (daylight-saving aware). The result keeps the same absolute instant:
 * Beijing 08:58 on a summer day becomes London 01:58, on a winter day 00:58.
 */
function convertHHMM(tzFrom, tzTo, hhmm, ref) {
    const date = ref || new Date();
    const wc = wallClock(tzFrom, date);
    const ms = wallToUTC(tzFrom, wc.y, wc.mo, wc.d, hhmm);
    return wallClock(tzTo, new Date(ms)).minutes;
}
/**
 * UTC offset of a timezone at the given instant, in minutes (DST-aware).
 * Correct at minute precision: interpret the timezone's wall-clock minute as
 * if it were UTC, and subtract the real UTC instant that wall-clock minute
 * maps to. E.g. Asia/Shanghai -> 480, Europe/London -> 60 in summer / 0 in
 * winter, America/New_York -> -240 in summer / -300 in winter.
 */
function utcOffsetMinutes(tz, date) {
    const wc = wallClock(tz, date);
    const tzMs = wallToUTC(tz, wc.y, wc.mo, wc.d, wc.minutes);
    const utcMs = Date.UTC(wc.y, wc.mo - 1, wc.d, Math.floor(wc.minutes / 60), wc.minutes % 60);
    return Math.round((utcMs - tzMs) / 60000);
}
/** True when the string is a valid IANA timezone name. */
function isValidTz(tz) {
    try {
        new Intl.DateTimeFormat('en-US', { timeZone: tz });
        return true;
    }
    catch (e) {
        return false;
    }
}
/** Window as half-open minute ranges (handles midnight-crossing). */
function rangesOf(w) {
    const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
    if (p < r)
        return [[p, r]];
    return [[p, 1440], [0, r]];
}
function rangesIntersect(a, b) {
    for (const sa of a)
        for (const sb of b) {
            if (sa[0] < sb[1] && sb[0] < sa[1])
                return true;
        }
    return false;
}
function daysOverlap(a, b) {
    const da = (a.days && a.days.length) ? a.days : [1, 2, 3, 4, 5, 6, 7];
    const db = (b.days && b.days.length) ? b.days : [1, 2, 3, 4, 5, 6, 7];
    return da.some((d) => db.includes(d));
}
/**
 * Validate a windows array: shape, HH:mm syntax, pause != resume, IANA
 * timezone, days 1-7, and same-timezone overlap (incl. midnight-crossing and
 * weekday-intersection cases).
 */
function validateWindows(windows, defaultTz) {
    if (!Array.isArray(windows))
        return { ok: false, error: 'windows must be an array' };
    for (const w of windows) {
        if (!w || typeof w !== 'object')
            return { ok: false, error: 'window must be an object' };
        if (parseHHMM(w.pauseAt) === null || parseHHMM(w.resumeAt) === null) {
            return { ok: false, error: 'bad HH:mm in window ' + JSON.stringify(w) };
        }
        if (parseHHMM(w.pauseAt) === parseHHMM(w.resumeAt)) {
            return { ok: false, error: 'pauseAt == resumeAt in window ' + JSON.stringify(w) };
        }
        if (w.timezone !== undefined && !isValidTz(w.timezone)) {
            return { ok: false, error: 'invalid IANA timezone: ' + w.timezone };
        }
        if (w.days !== undefined && (!Array.isArray(w.days) || !w.days.every((d) => Number.isInteger(d) && d >= 1 && d <= 7))) {
            return { ok: false, error: 'days must be array of 1-7' };
        }
    }
    for (let i = 0; i < windows.length; i++) {
        for (let j = i + 1; j < windows.length; j++) {
            const a = windows[i], b = windows[j];
            const aTz = a.timezone || defaultTz, bTz = b.timezone || defaultTz;
            if (aTz !== bTz)
                continue;
            if (!daysOverlap(a, b))
                continue;
            if (rangesIntersect(rangesOf(a), rangesOf(b))) {
                return { ok: false, error: 'overlapping windows: ' + JSON.stringify(a) + ' vs ' + JSON.stringify(b) };
            }
        }
    }
    return { ok: true };
}
/**
 * dsh-save-money — Account balance query (DeepSeek API /user/balance), Host side.
 * ...doc...
 */
/** Cache window; the header polls every 30s, so keep the upstream call rare. */
const CACHE_MS = 60000;
/** 余额采样周期:后端每 5 分钟记录一次余额。 */
const SAMPLE_MS = 5 * 60 * 1000;
/** 采样点上限:5min × 288 = 24 小时。 */
const HISTORY_LEN = 288;
/**
 * 余额历史队列:每 5 分钟一个采样点,保留最近 24 小时。
 * 用途:由余额变化计算「最近 1 小时 / 10 分钟 / 24 小时消费了多少钱」。
 *
 * 防膨胀保证(绝对上限,任何输入都不可能突破):
 *  - record() 先做输入校验:非有限数字(NaN / ±Infinity / 非数字)直接忽略,
 *    不会入队,也不可能污染 latest() / spend()。
 *  - 同一 5 分钟窗口内的再次 record 只更新最新值(不新增点)。
 *  - 时间戳乱序(倒退)一律不新增:at <= last.at 时视为同窗口更新,从根上
 *    杜绝乱序 push 破坏升序;只有严格递增且间隔 >= SAMPLE_MS 才新增。
 *  - push 后立即用 splice 强制裁剪到 HISTORY_LEN —— 即使某次批量 push 了
 *    多个点,数组长度也一次性回到上限内,峰值严格 <= HISTORY_LEN + 批量数,
 *    且 splice(0, overflow) 只发生一次。调用路径当前每次仅 push 1 个,
 *    所以实际峰值恒为 HISTORY_LEN + 1 = 289,随后即回到 288。
 */
function createBalanceHistory() {
    const points = [];
    const pushPoint = (at, total, activity) => {
        points.push({ at, total, ...(activity === undefined ? {} : { activity }) });
        if (points.length > HISTORY_LEN) {
            points.splice(0, points.length - HISTORY_LEN); // 一次裁掉全部溢出
        }
    };
    return {
        record(total, at = Date.now(), activity) {
            if (typeof at !== 'number' || !Number.isFinite(at))
                return;
            if (typeof total !== 'number' || !Number.isFinite(total))
                return;
            // 采样点对齐到整数 5 分钟(07:42:37 → 07:40):任何时区偏移都是整分钟,
            // 所以 ms % SAMPLE_MS == 0 在所有时区都落在整 5 分钟上 —— 与墙钟对齐,
            // 便于和官方后台(按整点计费)对比。对齐后同窗口的多次 record 共享同
            // 一个 at,自然落入「同刻更新」分支,去重语义与整数边界完全一致。
            at = at - (at % SAMPLE_MS);
            const last = points[points.length - 1];
            // 乱序(倒退或同刻)一律按同窗口更新,绝不新增:保持数组按 at 升序。
            if (last && at <= last.at) {
                last.total = total;
                if (activity !== undefined)
                    last.activity = activity;
                return;
            }
            if (last && at - last.at < SAMPLE_MS) {
                last.total = total;
                if (activity !== undefined)
                    last.activity = activity;
                return;
            }
            pushPoint(at, total, activity);
        },
        /** 最新一条余额,无采样时返回 null。 */
        latest() {
            return points.length > 0 ? points[points.length - 1].total : null;
        },
        /** now - ms 时刻的余额(取不晚于该时刻的最近采样);历史不足返回 null。 */
        totalAgo(ms, now = Date.now()) {
            if (typeof ms !== 'number' || !Number.isFinite(ms) || typeof now !== 'number' || !Number.isFinite(now))
                return null;
            const target = now - ms;
            for (let i = points.length - 1; i >= 0; i--) {
                if (points[i].at <= target)
                    return points[i].total;
            }
            return null;
        },
        /** 最近 ms 的消费金额(正数 = 花掉;余额回升时为负);历史不足返回 null。 */
        spend(ms, now = Date.now()) {
            const cur = this.latest();
            const prev = this.totalAgo(ms, now);
            if (cur === null || prev === null)
                return null;
            return prev - cur;
        },
        /** 当前全部采样点(调试/展示)。 */
        points() {
            return points.slice();
        },
        /** 用持久化的数据整体替换当前历史(启动时调用);空/非法输入忽略。 */
        load(persisted) {
            if (!Array.isArray(persisted) || persisted.length === 0)
                return;
            const clean = [];
            for (const p of persisted) {
                if (!p || typeof p.at !== 'number' || !Number.isFinite(p.at))
                    continue;
                if (typeof p.total !== 'number' || !Number.isFinite(p.total))
                    continue;
                // 对齐到整数 5 分钟(与 record 一致):旧版本可能存了任意时刻,载入后统一
                const aligned = p.at - (p.at % SAMPLE_MS);
                clean.push({ at: aligned, total: p.total, ...(p.activity === undefined ? {} : { activity: !!p.activity }) });
            }
            if (clean.length === 0)
                return;
            // 保证升序(持久化文件可能乱序)
            clean.sort((a, b) => a.at - b.at);
            // 去重(同一时刻保留最后一条)
            const deduped = [];
            for (const p of clean) {
                const last = deduped[deduped.length - 1];
                if (last && last.at === p.at)
                    deduped[deduped.length - 1] = p;
                else
                    deduped.push(p);
            }
            points.length = 0;
            for (const p of deduped.slice(-HISTORY_LEN))
                pushPoint(p.at, p.total, p.activity);
        },
        clear() { points.length = 0; },
    };
}
/**
 * 账户指纹:对 DeepSeek API key 做 FNV-1a 32 位散列(前 8 位十六进制)。
 * 仅用于「换 key = 换账户 = 旧历史作废」的身份比对,不是安全用途
 * (密钥本身不进持久化文件,也不会被这个哈希还原)。
 */
function keyFingerprint(key) {
    let h = 0x811c9dc5;
    for (let i = 0; i < key.length; i++) {
        h ^= key.charCodeAt(i);
        h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(16).padStart(8, '0');
}
/** 余额历史持久化文件名(用户目录 ~/.dsh 下,账户级、跨项目共享)。 */
const BALANCE_HISTORY_FILE = 'dsh-save-money-balance.json';
/** 序列化历史(供写盘)。 */
function serializeBalanceHistory(p) {
    return JSON.stringify({ keyId: p.keyId, points: p.points });
}
/** 解析持久化历史;非法 JSON / 非对象 / 结构不符返回 null(绝不 throw)。 */
function parseBalanceHistory(text) {
    try {
        const data = JSON.parse(text);
        if (!data || typeof data !== 'object' || typeof data.keyId !== 'string')
            return null;
        if (!Array.isArray(data.points))
            return null;
        return { keyId: data.keyId, points: data.points };
    }
    catch (e) {
        return null;
    }
}
/** 官方 DeepSeek provider 路由名(harness 硬编码)。 */
const OFFICIAL_PROVIDER = 'deepseek-official';
/**
 * 按 provider 名 + 模型名识别请求的档位。纯函数、永不抛异常:
 *  - 服务商:provider 小写含 'opencode' → OpenCode(go/zen 网关复用同路由);
 *    provider === 'deepseek-official' → 官方;其余 → null(豁免)。
 *  - 档位:模型名小写含 'pro' → pro;含 'flash' → flash;否则 null(豁免,
 *    包括旧名 chat/reasoner 与未知模型 —— 只有明确 flash/pro 才可能被暂停)。
 * 任何输入形态(undefined/非字符串)都安全返回 null。
 */
function classifyModel(provider, model) {
    const p = typeof provider === 'string' ? provider.toLowerCase() : '';
    const m = typeof model === 'string' ? model.toLowerCase() : '';
    if (p.length === 0 || m.length === 0)
        return null;
    const isPro = m.indexOf('pro') >= 0;
    const isFlash = m.indexOf('flash') >= 0;
    if (!isPro && !isFlash)
        return null; // unknown → 豁免
    if (p === OFFICIAL_PROVIDER)
        return isPro ? 'official-pro' : 'official-flash';
    if (p.indexOf('opencode') >= 0)
        return isPro ? 'opencode-pro' : 'opencode-flash';
    return null; // 其他第三方 → 豁免(它们没有 DeepSeek 峰谷策略)
}
/**
 * 查询某一档位在当前 modelApply 配置中是否勾选(是否应执行省钱)。
 * 配置缺省/损坏时返回 false(安全方向:不暂停);档位为 null 时恒 false。
 */
function modelApplyEnabled(applied, cls) {
    if (!applied || typeof applied !== 'object' || cls === null)
        return false;
    return applied[cls] === true;
}
/** tz 时区的墙钟分钟-of-day(0..1439)。内部工具,供时区对齐使用。 */
function tzMinutes(tz, date) {
    try {
        const f = new Intl.DateTimeFormat('en-US', {
            timeZone: tz, hour12: false,
            year: 'numeric', month: '2-digit', day: '2-digit',
            hour: '2-digit', minute: '2-digit', second: '2-digit',
        });
        const parts = {};
        for (const p of f.formatToParts(date))
            parts[p.type] = p.value;
        return Number(parts.hour) * 60 + Number(parts.minute);
    }
    catch (e) {
        return -1;
    } // 非法时区 → 调用方回退到 UTC 对齐
}
/** 把绝对时刻 ms 对齐到「tz 时区墙钟的整 step 分钟」。
 * 例如 tz=Asia/Shanghai、step=10min:任何时刻都对齐到 xx:00 / xx:10 / xx:20 …。
 * 关键:对齐基于**墙钟分钟**而不是 UTC 毫秒——对偏移非 10 分钟整倍数的
 * 时区(如 Asia/Kathmandu +5:45)也正确,柱边界恒显示为整数 10 分钟,
 * 与官方后台按当地整点计费的数据可比。DST 安全(基于实时区规则,不是
 * 固定偏移)。非法 tz 返回 undefined,调用方回退到 UTC 对齐。 */
function alignWallClock(tz, ms, stepMs) {
    const m = tzMinutes(tz, new Date(ms));
    if (m < 0)
        return undefined;
    const stepMin = Math.round(stepMs / 60000);
    if (!(stepMin >= 1))
        return undefined;
    const aligned = m - (m % stepMin);
    // 用对齐后的墙钟分钟求绝对时刻:先近似 UTC,再按 tz 规则迭代校正
    // (wallToUTC 的思路:对齐 DST 偏移造成的日差,再对分钟差)。
    const wc = (() => {
        const f = new Intl.DateTimeFormat('en-US', {
            timeZone: tz, hour12: false,
            year: 'numeric', month: '2-digit', day: '2-digit',
        });
        const parts = {};
        for (const p of f.formatToParts(new Date(ms)))
            parts[p.type] = p.value;
        return { y: Number(parts.year), mo: Number(parts.month), d: Number(parts.day) };
    })();
    let out = Date.UTC(wc.y, wc.mo - 1, wc.d, Math.floor(aligned / 60), aligned % 60);
    const targetDay = Date.UTC(wc.y, wc.mo - 1, wc.d);
    for (let i = 0; i < 8; i++) {
        const cur = tzMinutes(tz, new Date(out));
        if (cur === aligned)
            return out;
        const curDay = Date.UTC(Number(new Intl.DateTimeFormat('en-US', { timeZone: tz, year: 'numeric' }).format(new Date(out))), Number(new Intl.DateTimeFormat('en-US', { timeZone: tz, month: '2-digit' }).format(new Date(out))) - 1, Number(new Intl.DateTimeFormat('en-US', { timeZone: tz, day: '2-digit' }).format(new Date(out))));
        const dayDiff = Math.round((curDay - targetDay) / 86400000);
        if (dayDiff !== 0) {
            out -= dayDiff * 86400000;
            continue;
        }
        out += (aligned - cur) * 60000;
    }
    return out;
}
/**
 * 从余额采样点聚合「最近 8 小时、10 分钟一根」的消费柱形数据。
 * 每根柱 = 窗口起始时刻的余额 − 窗口结束时刻的余额(正=花掉,负=回升)。
 * 窗口边界对齐:tz 给定(推荐)时按**该时区墙钟的整 10 分钟**对齐,柱窗口
 * 恒为「07:40–07:50」「07:50–08:00」这类整数区间,与官方后台按当地整点
 * 计费的数据天然可比(DST 安全);tz 缺省或非法时回退到 UTC 对齐。
 * 窗口两端的余额取自不晚于该时刻的最近采样;任一端无采样,或两端取到
 * **同一个采样点**(该窗口内没有可观测的余额变化,历史覆盖不足),则该柱
 * 为 null——绝不用假 0 冒充"没有消费"。
 * activity:该柱时间窗内任一采样点带 activity=true 即为 true(本环境有活动)。
 * 数组从最近到最远排列(第 0 根是最近 10 分钟)。
 * 纯函数、不抛异常、长度恒为 count(默认 48 = 8 小时)。
 */
function spendBars(points, now = Date.now(), count = 48, barMs = 10 * 60 * 1000, tz) {
    // 返回不晚于 t 的最近采样索引;无则 -1。
    const indexAt = (t) => {
        for (let i = points.length - 1; i >= 0; i--) {
            if (points[i].at <= t)
                return i;
        }
        return -1;
    };
    // 对齐 now:优先按 tz 墙钟的整 barMs 分钟对齐(官方后台按当地整点计费);
    // tz 缺省/非法时回退到 UTC 对齐。
    const alignedNow = (tz ? alignWallClock(tz, now, barMs) : undefined) ?? (now - (now % barMs));
    const out = [];
    for (let i = 0; i < count; i++) {
        const end = alignedNow - i * barMs;
        const start = alignedNow - (i + 1) * barMs;
        const endIdx = indexAt(end);
        const startIdx = indexAt(start);
        // 任一端无采样,或两端是同一个采样点(窗口内无余额变化信息)→ null。
        const spent = (startIdx >= 0 && endIdx >= 0 && startIdx !== endIdx)
            ? points[startIdx].total - points[endIdx].total
            : null;
        // 窗口内(start..end] 任一采样点有活动 → 本环境活动为 true
        let activity = false;
        for (let j = Math.max(0, startIdx); j <= endIdx && j < points.length; j++) {
            if (points[j].activity === true) {
                activity = true;
                break;
            }
        }
        out.push({ at: start, spent, activity });
    }
    return out;
}
/** Hard ceiling for one upstream balance attempt (fetch or subprocess settle).
 * The DeepSeek /user/balance call normally returns in ~1s; a 5s bound gives
 * plenty of headroom while guaranteeing a hung child can never pin the plugin. */
const UPSTREAM_TIMEOUT_MS = 5000;
/**
 * Race a promise against a timeout so a hung subprocess or service call can
 * NEVER pin the balance service (and therefore the plugin) forever.
 */
function withTimeout(p, ms, message) {
    return new Promise((resolve, reject) => {
        const timer = setTimeout(() => reject(new Error(message)), ms);
        p.then((v) => { clearTimeout(timer); resolve(v); }, (e) => { clearTimeout(timer); reject(e); });
    });
}
/**
 * Create the balance service for one plugin instance.
 * @param ctx - plugin context (ctx.get for credentials / settings / subprocess).
 * @param opts.sandbox - true in the dynamic-plugin sandbox (no real fetch);
 *   false in the official module form (Node fetch available).
 */
function createBalanceService(ctx, opts) {
    let cache = null;
    let inFlight = null;
    return {
        query() {
            const now = Date.now();
            if (cache && now - cache.at < CACHE_MS)
                return Promise.resolve(cache.data);
            if (inFlight)
                return inFlight;
            inFlight = (async () => {
                let out;
                try {
                    const gate = await balanceAvailable(ctx);
                    out = gate.ok
                        ? await withTimeout(fetchBalance(ctx, opts.sandbox), UPSTREAM_TIMEOUT_MS, 'balance upstream timeout')
                        : { ok: false, error: gate.reason || 'balance not available' };
                }
                catch (e) {
                    out = { ok: false, error: String((e && e.message) || e) };
                }
                cache = { at: Date.now(), data: out };
                return out;
            })().finally(() => { inFlight = null; });
            return inFlight;
        },
    };
}
/**
 * Gate: only the official DeepSeek API offers /user/balance.
 *
 * The gate checks the DeepSeek provider's OWN configuration (baseURL must be
 * the official endpoint, or unset to use the official default), NOT the
 * session's current default model. Users routinely configure several model
 * sources (official DeepSeek + SiliconFlow / relays / …) and switch the
 * default model between them; the balance is a property of the official
 * DeepSeek account, so it stays queryable regardless of which provider the
 * current model belongs to. If the official baseURL is overridden to a relay
 * (no /user/balance endpoint), the gate rejects so the UI does not show a
 * misleading balance.
 */
async function balanceAvailable(ctx) {
    try {
        const settings = ctx.get('settings');
        const sec = settings && typeof settings.get === 'function' ? settings.get('llm-deepseek') : undefined;
        const base = sec && typeof sec === 'object' && typeof sec.baseURL === 'string' ? sec.baseURL : '';
        if (base && !/^https?:\/\/api\.deepseek\.com\/?$/.test(String(base).trim())) {
            return { ok: false, reason: 'llm-deepseek baseURL is not the official API: ' + String(base) };
        }
    }
    catch (e) { /* settings unavailable — assume official default */ }
    return { ok: true };
}
/** One balance request (no caching; see the service wrapper). */
async function fetchBalance(ctx, sandbox) {
    const creds = ctx.get('credentials');
    const key = creds && typeof creds.resolve === 'function'
        ? await creds.resolve('DEEPSEEK_API_KEY').then((r) => r && r.value).catch(() => undefined)
        : undefined;
    if (!key)
        return { ok: false, error: 'no DEEPSEEK_API_KEY credential' };
    const url = 'https://api.deepseek.com/user/balance';
    try {
        let status = 0;
        let text = '';
        if (!sandbox && typeof fetch === 'function') {
            // Official module form runs in Node: real fetch is available.
            const res = await fetch(url, {
                headers: { authorization: 'Bearer ' + key, accept: 'application/json' },
                signal: typeof AbortSignal !== 'undefined' && AbortSignal && typeof AbortSignal.timeout === 'function'
                    ? AbortSignal.timeout(10000)
                    : undefined,
            });
            status = res.status;
            text = await res.text();
        }
        else {
            // Dynamic sandbox: `fetch` exists but is a guard stub that throws on
            // call — run curl via the subprocess service. Any shape mismatch fails
            // closed (ok:false) and can never throw out of this function.
            const sub = ctx.get('subprocess');
            if (!sub || typeof sub.spawn !== 'function') {
                return { ok: false, error: 'no fetch or subprocess available for balance' };
            }
            let done = null;
            let raw = '';
            try {
                const handle = sub.spawn({
                    argv: ['curl', '-sS', '-f', '-m', '10', '-H', 'Authorization: Bearer ' + key, url],
                    cwd: '.',
                    stdio: { stdin: 'ignore', stdout: { maxBytes: 65536 }, stderr: { maxBytes: 4096 } },
                    graceMs: 12000,
                });
                // handle.done is the settle result (awaitable); some spawn flavors
                // expose it as a function — support both shapes. A hard timeout keeps
                // a hung curl from ever pinning the balance query: on timeout we try
                // to kill the child (best-effort) and fail closed.
                const settle = typeof handle.done === 'function'
                    ? withTimeout(Promise.resolve(handle.done()), UPSTREAM_TIMEOUT_MS, 'balance curl timeout')
                    : withTimeout(Promise.resolve(handle.done), UPSTREAM_TIMEOUT_MS, 'balance curl timeout');
                done = await settle;
                try {
                    if (handle && typeof handle.kill === 'function')
                        handle.kill();
                }
                catch (e) { /* best-effort */ }
                const collected = handle.collected && handle.collected.stdout;
                raw = collected && typeof collected.readFrom === 'function'
                    ? collected.readFrom(0).text
                    : '';
            }
            catch (e) {
                return { ok: false, error: 'balance subprocess failed: ' + String((e && e.message) || e) };
            }
            // curl's exit code is NOT an HTTP status: with -f, exit 0 means the
            // request succeeded (2xx), non-zero means an HTTP error or transport
            // failure. Map exit 0 -> 200 so the ok check below works; anything else
            // keeps the non-zero code and fails the ok check.
            status = done && done.exitCode === 0 ? 200 : (done && typeof done.exitCode === 'number' ? done.exitCode : 0);
            text = raw || '';
        }
        let data = null;
        try {
            data = JSON.parse(text);
        }
        catch (e) { /* non-JSON body */ }
        if (data && typeof data === 'object' && Array.isArray(data.balance_infos)) {
            return {
                ok: status >= 200 && status < 300,
                httpStatus: status,
                available: data.is_available === true,
                balance: data.balance_infos.map((b) => ({
                    currency: b.currency,
                    total: b.total_balance,
                    granted: b.granted_balance,
                    toppedUp: b.topped_up_balance,
                })),
            };
        }
        return { ok: false, httpStatus: status, error: 'unexpected response: ' + text.slice(0, 200) };
    }
    catch (e) {
        return { ok: false, error: String((e && e.message) || e) };
    }
}

export function apply(ctx) {
        const DEFAULTS = {
            enabled: false,
            timezone: 'Asia/Shanghai',
            warnMinutes: 5,
            windows: [],
            reconcileOnStart: true,
            lang: 'auto',
            showBalance: false,
            // v1.4.1:按模型档位决定是否执行省钱。默认只勾官方两项 —— 全新用户
            // 启用省钱只作用于官方 flash/pro;OpenCode(订阅套餐)与未知模型默认
            // 豁免,用户主动勾选才暂停。用户改过配置后尊重持久化值,绝不重置。
            modelApply: {
                'official-flash': true,
                'official-pro': true,
                'opencode-flash': false,
                'opencode-pro': false,
            },
        };
        let cfg = { ...DEFAULTS, windows: [] };
        let pauseRecord = null;
        // "End this save mode" state — one-shot, in-memory only (never persisted):
        // applies to the exact window it was invoked for (matched by key), expires
        // at that window's resumeAt, and leaves the persistent `enabled` flag
        // untouched. The next window (today or later) is unaffected.
        let endWindowUntil = 0;
        let endWindowKey = null;
        let lastStateKey = 'NORMAL';
        let configLoaded = false;
        let configPath = '';
        const unwrap = (args) => (args && typeof args === 'object' && args.arguments && typeof args.arguments === 'object' ? args.arguments : args);
        // Config persistence to the workspace file (survives browser refresh /
        // plugin re-activation). The config location is resolved AT RUNTIME by
        // walking a candidate list (see candidateRoots) — session cwd first, then
        // process cwd and its sibling directory (the README quick-install layout
        // ~/app/dsh-save-money next to ~/app/deepseek-harness), then the
        // sandboxPolicy fallback. The FIRST directory that actually contains a
        // save-money.config.json wins; a pointer file in the DSH user dir
        // (~/.dsh/save-money-config-path.json) records the last real location so
        // a later restart resolves the SAME file even when no session cwd matches
        // (e.g. the harness was started from a different directory). No machine
        // path is ever hard-coded.
        const CONFIG_FILE = 'save-money.config.json';
        const POINTER_FILE = 'save-money-config-path.json';
        // Services are read DYNAMICALLY on every use, not captured once at apply():
        // the official bundle form (plugin/index.js) is a plugin row that can be
        // activated BEFORE the base bundle's fs-sandbox / sandbox-policy / sessions
        // rows (Cordis activation order is composition order, and the user's plugin
        // row is inserted into the profile alongside them). A one-shot
        // `const fs = ctx.get('fs')` would permanently capture `undefined` on such
        // machines — exactly the "settings never persist / never load" report on a
        // second computer. Each helper re-reads the service at call time, and the
        // boot path also waits via ctx.inject(['fs']) (see startup below), so a
        // late fs service is picked up as soon as it exists.
        const getFs = () => ctx.get('fs');
        const getSessions = () => ctx.get('sessions');
        const getAgents = () => ctx.get('agents');
        const getSandboxPolicy = () => ctx.get('sandboxPolicy');
        const defaultWorkspaceRoot = (() => {
            const sandboxPolicy = getSandboxPolicy();
            return (sandboxPolicy && typeof sandboxPolicy.workspaceRoot === 'string' && sandboxPolicy.workspaceRoot.length > 0)
                ? sandboxPolicy.workspaceRoot
                : '';
        })();
        // sandboxPolicy.workspaceRoot is the process cwd (the DSH install dir), not
        // the session workspace. The plugin config belongs to the save-money
        // workspace, so prefer a session whose cwd points at this repo (matched by
        // directory basename only — no machine path is hard-coded).
        const sessionCwdOf = (s) => {
            const c = s && (s.meta && s.meta.cwd || s.header && s.header.cwd || s.cwd);
            return typeof c === 'string' ? c : '';
        };
        // DSH user dir (~/.dsh): exists on Windows / macOS / Linux. The pointer
        // file lives here because it is the one location that never moves with the
        // harness install dir or the session cwd.
        const dshHome = () => {
            try {
                const h = (typeof process !== 'undefined' && process && process.env)
                    ? (process.env.DSH_HOME || process.env.USERPROFILE || process.env.HOME)
                    : '';
                return typeof h === 'string' && h.length > 0 ? h.replace(/[\\/]+$/, '') : '';
            }
            catch (e) {
                return '';
            }
        };
        // Read the pointer file (best-effort; '' when absent/unreadable).
        const readPointer = async () => {
            const home = dshHome();
            const fs = getFs();
            if (!home || !fs)
                return '';
            try {
                const target = await fs.resolve(POINTER_FILE, { cwd: home });
                const text = await fs.readText(target);
                const data = JSON.parse(text);
                const p = data && typeof data.path === 'string' ? data.path : '';
                return p.replace(/[\\/]+$/, '');
            }
            catch (e) {
                return '';
            }
        };
        // Record the last real config dir in ~/.dsh (best-effort; never throws).
        const writePointer = async (dir) => {
            const home = dshHome();
            const fs = getFs();
            if (!home || !fs || !dir)
                return;
            try {
                const target = await fs.resolve(POINTER_FILE, { cwd: home });
                await fs.writeText(target, JSON.stringify({ path: dir }, null, 2), undefined, undefined, { mode: 'workspace-write', workspaceRoot: home });
            }
            catch (e) { /* best-effort */ }
        };
        // Candidate config directories, highest priority first. The pointer (the
        // last real location) is handled separately in resolveWorkspaceRoot.
        const candidateRoots = () => {
            const out = [];
            const push = (c) => {
                c = String(c || '').replace(/[\\/]+$/, '');
                if (c && !out.includes(c))
                    out.push(c);
            };
            // ① the calling session (agents.currentInitiator): the session that
            //    actually uses the plugin, so config follows the user's workspace.
            try {
                const agentsSvc = getAgents();
                const init = agentsSvc && typeof agentsSvc.currentInitiator === 'function'
                    ? agentsSvc.currentInitiator()
                    : undefined;
                const sessionsSvc = getSessions();
                if (init && sessionsSvc && typeof sessionsSvc.get === 'function') {
                    push(sessionCwdOf(sessionsSvc.get(init.id) || init));
                }
            }
            catch (e) { /* skip */ }
            // ② every session whose cwd matches the repo basename (last wins, so
            //    the newest checkout is preferred when several exist).
            const sessionsSvc = getSessions();
            if (sessionsSvc && typeof sessionsSvc.list === 'function') {
                try {
                    const matches = [];
                    for (const s of sessionsSvc.list()) {
                        const c = sessionCwdOf(s).replace(/[\\/]+$/, '');
                        if (/dsh-save-money$/i.test(c))
                            matches.push(c);
                    }
                    for (const m of matches)
                        push(m);
                }
                catch (e) { /* skip */ }
            }
            // ③ process.cwd() itself (official module form only; the harness may be
            //    started from the repo checkout).
            try {
                if (typeof process !== 'undefined' && process && typeof process.cwd === 'function') {
                    push(String(process.cwd()));
                }
            }
            catch (e) { /* skip */ }
            // ④ sibling of process.cwd() named dsh-save-money — the README
            //    quick-install layout: ~/app/dsh-save-money next to
            //    ~/app/deepseek-harness, harness started from the latter.
            try {
                if (typeof process !== 'undefined' && process && typeof process.cwd === 'function') {
                    const cwd = String(process.cwd()).replace(/[\\/]+$/, '');
                    const idx = Math.max(cwd.lastIndexOf('\\'), cwd.lastIndexOf('/'));
                    if (idx > 0)
                        push(cwd.slice(0, idx + 1) + 'dsh-save-money');
                }
            }
            catch (e) { /* skip */ }
            // ⑤ sandboxPolicy fallback (the harness install dir).
            push(defaultWorkspaceRoot);
            return out;
        };
        // The last successfully used config dir (for status diagnostics + write
        // targeting without re-resolving on every call).
        let resolvedConfigDir = '';
        const resolveWorkspaceRoot = async () => {
            const fs = getFs();
            if (!fs)
                return defaultWorkspaceRoot;
            // ① pointer file: the last real location wins, so a restart resolves the
            //    same file even when no session cwd matches (the harness was started
            //    from a different directory than the repo).
            const ptr = await readPointer();
            if (ptr) {
                try {
                    await fs.readText(await fs.resolve(CONFIG_FILE, { cwd: ptr }));
                    resolvedConfigDir = ptr;
                    return ptr;
                }
                catch (e) { /* pointer stale — fall through to candidates */ }
            }
            const roots = candidateRoots();
            for (const dir of roots) {
                if (!dir)
                    continue;
                try {
                    await fs.readText(await fs.resolve(CONFIG_FILE, { cwd: dir }));
                    resolvedConfigDir = dir;
                    return dir;
                }
                catch (e) { /* no config here — try next */ }
            }
            // No config exists anywhere yet: prefer a repo-named candidate (the
            // sibling-directory layout from the README, or a session cwd), so a
            // fresh install writes next to the checkout instead of polluting the
            // harness install dir; fall back to the first candidate.
            let target = '';
            for (const dir of roots) {
                if (dir && /dsh-save-money$/i.test(dir)) {
                    target = dir;
                    break;
                }
            }
            resolvedConfigDir = target || roots[0] || defaultWorkspaceRoot;
            return resolvedConfigDir;
        };
        const windowKey = (w, tz) => w.pauseAt + '|' + w.resumeAt + '|' + (w.timezone || tz);
        const persistConfig = async () => {
            const fs = getFs();
            if (!fs) {
                console.error('[save-money] persist skipped: fs service unavailable');
                return;
            }
            try {
                const workspaceRoot = await resolveWorkspaceRoot();
                if (!workspaceRoot)
                    return;
                const resolveOpts = { cwd: workspaceRoot };
                const writePolicy = { mode: 'workspace-write', workspaceRoot };
                const target = await fs.resolve(CONFIG_FILE, resolveOpts);
                configPath = fs.processPath ? String(fs.processPath(target)) : String(target && (target.path || target.filePath || ''));
                await fs.writeText(target, JSON.stringify(snapshot(), null, 2), undefined, undefined, writePolicy);
                await writePointer(workspaceRoot);
                console.log('[save-money] config persisted to ' + workspaceRoot + '\\' + CONFIG_FILE);
            }
            catch (e) {
                console.error('[save-money] persist failed: ' + String((e && e.message) || e));
            }
        };
        const loadConfig = async () => {
            const fs = getFs();
            if (!fs) {
                console.error('[save-money] load skipped: fs service unavailable');
                return;
            }
            try {
                const workspaceRoot = await resolveWorkspaceRoot();
                if (!workspaceRoot)
                    return;
                const resolveOpts = { cwd: workspaceRoot };
                const target = await fs.resolve(CONFIG_FILE, resolveOpts);
                configPath = fs.processPath ? String(fs.processPath(target)) : String(target && (target.path || target.filePath || ''));
                const text = await fs.readText(target);
                const data = JSON.parse(text);
                configLoaded = true;
                const next = { ...cfg };
                if (typeof data.enabled === 'boolean')
                    next.enabled = data.enabled;
                if (typeof data.timezone === 'string' && isValidTz(data.timezone))
                    next.timezone = data.timezone;
                if (typeof data.warnMinutes === 'number' && data.warnMinutes >= 0)
                    next.warnMinutes = data.warnMinutes;
                if (typeof data.reconcileOnStart === 'boolean')
                    next.reconcileOnStart = data.reconcileOnStart;
                if (typeof data.showBalance === 'boolean')
                    next.showBalance = data.showBalance;
                if (data.lang === 'auto' || data.lang === 'zh' || data.lang === 'zh-TW' || data.lang === 'en' ||
                    data.lang === 'de' || data.lang === 'fr' || data.lang === 'es' || data.lang === 'it' ||
                    data.lang === 'pt' || data.lang === 'ja' || data.lang === 'ko')
                    next.lang = data.lang;
                if (Array.isArray(data.windows)) {
                    const v = validateWindows(data.windows, next.timezone);
                    if (v.ok)
                        next.windows = data.windows.map((w) => ({ ...w }));
                }
                // modelApply:仅当用户保存过才采用(逐档校验 boolean,只合并合法档位,
                // 损坏/缺失的档位保持默认)。没有该字段 → 保持默认(官方两项勾选)。
                if (data.modelApply && typeof data.modelApply === 'object') {
                    const ma = { ...next.modelApply };
                    for (const key of ['official-flash', 'official-pro', 'opencode-flash', 'opencode-pro']) {
                        if (typeof data.modelApply[key] === 'boolean')
                            ma[key] = data.modelApply[key];
                    }
                    next.modelApply = ma;
                }
                cfg = next;
                console.log('[save-money] config loaded from ' + workspaceRoot + '\\' + CONFIG_FILE);
            }
            catch (e) {
                console.log('[save-money] no config file (fresh start): ' + String((e && e.message) || e));
            }
        };
        // ---------- Config ----------
        // Pure helpers (wallClock / parseHHMM / windowMatchesAt / nextPause /
        // wallToUTC / isValidTz / validateWindows) live in src/core.ts and are
        // inlined into this body at build time; see the declarations above.
        function applyConfig(patch) {
            const next = { ...cfg, ...patch };
            if (next.windows === undefined)
                next.windows = [];
            const v = validateWindows(next.windows, next.timezone);
            if (!v.ok)
                return { ok: false, error: v.error };
            if (next.timezone !== undefined && !isValidTz(next.timezone)) {
                return { ok: false, error: 'invalid IANA timezone: ' + next.timezone };
            }
            if (next.warnMinutes !== undefined && (!Number.isFinite(next.warnMinutes) || next.warnMinutes < 0)) {
                return { ok: false, error: 'warnMinutes must be >= 0' };
            }
            if (next.showBalance !== undefined && typeof next.showBalance !== 'boolean') {
                return { ok: false, error: 'showBalance must be a boolean' };
            }
            // modelApply:接受对象,逐档必须是 boolean(缺档保持原值)
            if (next.modelApply !== undefined) {
                if (!next.modelApply || typeof next.modelApply !== 'object') {
                    return { ok: false, error: 'modelApply must be an object' };
                }
                for (const key of ['official-flash', 'official-pro', 'opencode-flash', 'opencode-pro']) {
                    if (next.modelApply[key] !== undefined && typeof next.modelApply[key] !== 'boolean') {
                        return { ok: false, error: 'modelApply.' + key + ' must be a boolean' };
                    }
                }
            }
            const LANGS = ['auto', 'zh', 'zh-TW', 'en', 'de', 'fr', 'es', 'it', 'pt', 'ja', 'ko'];
            if (next.lang !== undefined && !LANGS.includes(next.lang)) {
                return { ok: false, error: 'lang must be one of auto/zh/zh-TW/en/de/fr/es/it/pt/ja/ko' };
            }
            // Re-activation resets the one-shot "end this save mode" state: when
            // `enabled` goes false -> true, clear endWindowUntil/endWindowKey so
            // every window takes effect again. The user gets a deterministic way to
            // re-arm saving money (e.g. after skipping a window during a test) by
            // toggling the Enable switch off and on.
            if (patch && patch.enabled === true && !cfg.enabled) {
                endWindowUntil = 0;
                endWindowKey = null;
                console.log('[save-money] re-enabled: end-this-save-mode state reset');
            }
            // modelApply 逐档合并:patch 只覆盖给定的档位,其余保留当前值,
            // 避免 { modelApply: { 'opencode-pro': true } } 丢掉官方两项。
            if (patch && patch.modelApply && typeof patch.modelApply === 'object') {
                const merged = { ...cfg.modelApply };
                for (const key of ['official-flash', 'official-pro', 'opencode-flash', 'opencode-pro']) {
                    if (typeof patch.modelApply[key] === 'boolean')
                        merged[key] = patch.modelApply[key];
                }
                next.modelApply = merged;
            }
            cfg = next;
            // Wake waiters only when the gate is actually open (unconditional wake
            // released suspended requests inside the window — observed as "still
            // thinking after pause" caused by the tick releasing every 60s).
            if (!gateClosedAt(new Date()))
                wakeGateWaiters();
            void persistConfig(); // persist on every config change
            return { ok: true, config: snapshot() };
        }
        function snapshot() {
            return {
                enabled: cfg.enabled,
                timezone: cfg.timezone,
                warnMinutes: cfg.warnMinutes,
                reconcileOnStart: cfg.reconcileOnStart,
                lang: cfg.lang,
                showBalance: cfg.showBalance,
                modelApply: { ...cfg.modelApply },
                windows: cfg.windows.map((w) => ({ ...w })),
            };
        }
        // ---------- Busy detection / freeze / resume ----------
        function collectTasks() {
            const agents = ctx.get('agents');
            const goals = ctx.get('goals');
            if (!agents || !goals)
                return { ok: false, tasks: [], reason: 'agents/goals services unavailable' };
            const tasks = [];
            for (const agent of agents.list()) {
                let gv = undefined;
                try {
                    gv = goals.get(agent);
                }
                catch (e) {
                    gv = undefined;
                }
                if (gv && (gv.phase === 'active' || (pauseRecord && pauseRecord.paused && pauseRecord.paused.some((p) => p.sessionId === agent.id)))) {
                    tasks.push({ agent, sessionId: agent.id, goalId: gv.id, revision: gv.revision, phase: gv.phase });
                }
            }
            return { ok: true, tasks };
        }
        function freeze(window) {
            const col = collectTasks();
            if (!col.ok) {
                console.error('[save-money] freeze skipped:', col.reason);
                return { frozen: 0, record: null };
            }
            const freezeTargets = col.tasks.filter((t) => t.phase === 'active');
            if (freezeTargets.length === 0) {
                console.log('[save-money] pauseAt reached but no active tasks; not pausing');
                return { frozen: 0, record: null };
            }
            const goals = ctx.get('goals');
            const paused = [];
            for (const t of freezeTargets) {
                try {
                    goals.pause(t.agent, { id: t.goalId, revision: t.revision });
                    paused.push({ sessionId: t.sessionId, goalId: t.goalId, revision: t.revision, pausedAt: Date.now() });
                }
                catch (e) {
                    console.error('[save-money] goals.pause failed for ' + t.sessionId + ': ' + String((e && e.message) || e));
                }
            }
            pauseRecord = {
                pausedBySaveMoney: true,
                at: new Date().toISOString(),
                window: window ? { pauseAt: window.pauseAt, resumeAt: window.resumeAt, timezone: window.timezone || cfg.timezone } : null,
                paused,
                cascaded: true,
            };
            console.log('[save-money] FROZEN ' + paused.length + ' goal(s), record written');
            return { frozen: paused.length, record: pauseRecord };
        }
        function unfreeze() {
            if (!pauseRecord)
                return { resumed: 0, record: null };
            const agents = ctx.get('agents');
            const goals = ctx.get('goals');
            const remaining = [];
            let resumed = 0;
            const targets = pauseRecord.paused || [];
            for (const p of targets) {
                const agent = agents && agents.get(p.sessionId);
                if (!agent)
                    continue;
                try {
                    const gv = goals.get(agent);
                    if (gv && gv.phase === 'paused') {
                        goals.resume(agent, { id: gv.id, revision: gv.revision });
                        resumed++;
                    }
                    else if (gv && gv.phase === 'active') {
                        resumed++;
                    }
                }
                catch (e) {
                    console.error('[save-money] goals.resume failed for ' + p.sessionId + ': ' + String((e && e.message) || e));
                    remaining.push(p);
                }
            }
            pauseRecord = remaining.length > 0 ? { ...pauseRecord, paused: remaining } : null;
            console.log('[save-money] RESUMED ' + resumed + ' goal(s)' + (remaining.length > 0 ? ', ' + remaining.length + ' still pending' : ', record cleared'));
            return { resumed, record: pauseRecord };
        }
        ctx.effect(() => {
            return () => {
                if (pauseRecord && pauseRecord.paused && pauseRecord.paused.length > 0) {
                    console.log('[save-money] plugin unloading: restoring paused goals');
                    unfreeze();
                }
            };
        });
        // ---------- State computation ----------
        function computeRawState(now) {
            if (!cfg.enabled)
                return { name: 'NORMAL', reason: 'disabled' };
            for (const w of cfg.windows) {
                const tz = w.timezone || cfg.timezone;
                if (windowMatchesAt(w, wallClock(tz, now))) {
                    // "End this save mode" only affects the exact window it was applied
                    // to — a stale endWindowUntil must not suppress later windows.
                    if (endWindowUntil > now.getTime() && endWindowKey === windowKey(w, tz))
                        return { name: 'NORMAL', reason: 'ended', window: w };
                    return { name: 'PAUSED', window: w };
                }
            }
            let nearest = null;
            for (const w of cfg.windows) {
                const tz = w.timezone || cfg.timezone;
                const wc = wallClock(tz, now);
                const np = nextPause(w, tz, wc);
                if (!np)
                    continue;
                const delta = np.dayOffset * 1440 + np.minutes - wc.minutes;
                if (nearest === null || delta < nearest.delta)
                    nearest = { delta, window: w };
            }
            if (nearest !== null && nearest.delta > 0 && nearest.delta <= cfg.warnMinutes) {
                // The upcoming window may already be ended via "end this save mode"
                // (clicked while WARN) — do not keep showing "pause soon", suppress it
                // until the window's own resumeAt.
                if (endWindowUntil > now.getTime() && endWindowKey === windowKey(nearest.window, nearest.window.timezone || cfg.timezone)) {
                    return { name: 'NORMAL', reason: 'ended', window: nearest.window };
                }
                return { name: 'WARN', window: nearest.window, minutesToPause: nearest.delta };
            }
            return { name: 'NORMAL', reason: 'no-window' };
        }
        function onTick(now) {
            const raw = computeRawState(now);
            let st = raw;
            if (raw.name === 'PAUSED') {
                if (!pauseRecord) {
                    const col = collectTasks();
                    if (!col.ok || col.tasks.length === 0)
                        st = { name: 'NORMAL', reason: 'no-task' };
                }
            }
            const key = st.name + (st.window ? ':' + st.window.pauseAt : '');
            if (key !== lastStateKey) {
                const prevName = lastStateKey.split(':')[0];
                lastStateKey = key;
                if (st.name === 'PAUSED' && prevName !== 'PAUSED') {
                    freeze(st.window);
                }
                else if (st.name !== 'PAUSED' && prevName === 'PAUSED') {
                    unfreeze();
                }
                console.log('[save-money] state -> ' + key);
            }
        }
        // ---------- Request-level gate (event-driven suspension; never throws,
        //            zero timer dependencies) ----------
        // Inside a pause window every streaming model call is intercepted (llm/stream
        // is the mandatory waterfall every call goes through). The gate uses the
        // same "inside window and not ignored" check as the state machine, and does
        // NOT depend on the freeze record: even when no active goal is frozen,
        // manual-conversation model requests are still suspended — that is
        // the saving-money semantics.
        // Implementation notes:
        //  - Cordis 3 registration API is ctx.on only; llm.stream dispatches via
        //    ctx.waterfall, and listeners must synchronously return an AsyncIterable
        //    (the caller for-await's it; an async listener would break the return
        //    type). So we return a WRAPPER stream: iteration waits for the gate to
        //    open first, then calls next() to get the real stream — options pass
        //    through untouched, routing/retry/validation are unaffected (we are
        //    registered at the chain tail; the suspend happens before the actual
        //    adapterStream).
        //  - The sandbox has no Node timer globals (setTimeout throws and fails the
        //    turn as "this run failed"); ctx.timer.timeout is a fiber effect and can
        //    still throw when registered inside an agent-turn fiber context. So
        //    waiting is EVENT-DRIVEN: suspending = registering the resolve into
        //    gateWaiters, woken by: ① the 60s tick (registered in the plugin apply
        //    context, runs reliably); ② applyConfig (disable / window change);
        //    ③ endWindowHandler (end-window); ④ plugin unload (fail-open); ⑤ request
        //    signal abort. No timers / fiber-effect calls → cannot throw, cannot
        //    interrupt a turn.
        let gateDisposed = false;
        let gateWaiters = [];
        const wakeGateWaiters = () => {
            const waiters = gateWaiters;
            gateWaiters = [];
            for (const release of waiters) {
                // Each waiter synchronously calls next() inside release(); if the
                // waterfall chain (DSH's own llm/stream invariants run first) throws
                // synchronously — e.g. the request context was torn down while the
                // gate held it — the exception must NOT escape into the host callback
                // that woke us (60s tick / applyConfig / unload). That would surface as
                // an uncaughtException and crash the harness. We swallow it here; the
                // pending request then rejects with the same error via the promise.
                try {
                    release();
                }
                catch (e) {
                    console.error('[save-money] gate release failed: ' + String((e && e.message) || e));
                }
            }
        };
        const gateClosedAt = (now) => {
            if (!cfg.enabled)
                return false;
            // The gate follows the state machine exactly: computeRawState already
            // exempts the ended window (endWindowKey match + endWindowUntil), so a
            // different window (e.g. cross-timezone overlap) stays gated.
            const st = computeRawState(now);
            return st.name === 'PAUSED';
        };
        const gateInstalled = typeof ctx.on === 'function';
        // "User sent a message" signal for the balance display: every llm/stream
        // request corresponds to fresh user activity, so mark the balance stale —
        // the client refreshes it on the next poll (message-driven update; the
        // 10-minute timer is the client-side fallback cadence).
        // lastRequestProvider records the provider of the MOST RECENT model
        // request (multi-provider setups: DeepSeek + SiliconFlow/relays). The
        // balance is a property of the official DeepSeek account, so it stays
        // shown only while the latest actual request ran on the official provider;
        // a switch to another provider hides it WITHOUT clearing the sampled
        // history, so switching back re-shows it immediately.
        let balanceDirty = false;
        let lastRequestProvider = null;
        if (typeof ctx.on === 'function') {
            ctx.effect(() => {
                const dispose = ctx.on('llm/stream', (options, next) => {
                    balanceDirty = true;
                    lastActivityAt = Date.now(); // 活动信号:本环境正在产生模型请求
                    try {
                        lastRequestProvider = (options && typeof options.provider === 'string' && options.provider.length > 0)
                            ? options.provider
                            : null;
                    }
                    catch (e) {
                        lastRequestProvider = null;
                    }
                    // v1.4.1 模型档位豁免:识别请求的 provider/model 档位,若该档位在
                    // modelApply 中未勾选(或识别失败=null),直接放行 —— 窗口内也不
                    // 暂停。豁免的请求同样算「本环境活动」(balanceDirty/activity 已
                    // 在上方打点),因为它确实是真实使用。识别/查询任何异常都安全失败
                    // 为豁免(不暂停),绝不抛出。
                    try {
                        const cls = classifyModel(options && options.provider, options && options.model);
                        if (!modelApplyEnabled(cfg.modelApply, cls))
                            return next();
                    }
                    catch (e) { /* 识别异常 → 豁免(不暂停) */ }
                    if (!gateClosedAt(new Date()))
                        return next();
                    const waitForOpen = () => new Promise((resolve) => {
                        const ready = () => gateDisposed || !gateClosedAt(new Date())
                            || !!(options && options.signal && options.signal.aborted);
                        // Release helper: call next() defensively. A synchronous throw from
                        // the waterfall chain (request context torn down / invariant fail)
                        // must surface as a rejected promise — never as an exception
                        // escaping into the abort event dispatch or wakeGateWaiters.
                        const release = () => {
                            try {
                                resolve(next());
                            }
                            catch (e) {
                                resolve(Promise.reject(e));
                            }
                        };
                        if (ready())
                            return release();
                        const waiter = () => { release(); };
                        gateWaiters.push(waiter);
                        if (options && options.signal && typeof options.signal.addEventListener === 'function') {
                            options.signal.addEventListener('abort', () => {
                                const i = gateWaiters.indexOf(waiter);
                                if (i >= 0)
                                    gateWaiters.splice(i, 1);
                                release();
                            }, { once: true });
                        }
                    });
                    // Wrapper stream: iteration waits only when the gate is closed; once
                    // open → next() → the real request proceeds as usual.
                    let inner = null;
                    const getInner = () => (inner !== null ? Promise.resolve(inner) : waitForOpen().then((s) => { inner = s; return inner; }));
                    return {
                        [Symbol.asyncIterator]() {
                            let it = null;
                            return {
                                next() {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.next();
                                    });
                                },
                                return(value) {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.return ? it.return(value) : { done: true, value };
                                    });
                                },
                                throw(e) {
                                    return getInner().then((s) => {
                                        if (!it)
                                            it = s[Symbol.asyncIterator]();
                                        return it.throw ? it.throw(e) : { done: true, value: e };
                                    });
                                },
                            };
                        },
                    };
                }, { global: true });
                return () => {
                    gateDisposed = true;
                    try {
                        wakeGateWaiters();
                    }
                    catch (e) { /* unload must never throw */ }
                    dispose();
                };
            });
        }
        else {
            console.error('[save-money] ctx.on unavailable; llm/stream gate not installed');
        }
        // ---------- Startup reconciliation ----------
        function reconcile() {
            const col = collectTasks();
            if (!col.ok)
                return { restored: 0, reason: col.reason };
            const goals = ctx.get('goals');
            const agents = ctx.get('agents');
            let restored = 0;
            for (const agent of agents.list()) {
                let gv = undefined;
                try {
                    gv = goals.get(agent);
                }
                catch (e) {
                    gv = undefined;
                }
                if (gv && gv.phase === 'paused') {
                    try {
                        goals.resume(agent, { id: gv.id, revision: gv.revision });
                        restored++;
                        console.log('[save-money] reconcile: restored paused goal of ' + agent.id);
                    }
                    catch (e) {
                        console.error('[save-money] reconcile resume failed for ' + agent.id + ': ' + String((e && e.message) || e));
                    }
                }
            }
            return { restored };
        }
        // ---- Owned timers (explicitly disposed on unload) ----
        // ctx.timer.timeout/interval are fiber effects and *should* be cleaned up
        // automatically when the fiber disposes, but hot-updates (run/update) are
        // the one path where we do NOT rely on implicit cleanup: save both
        // disposers and call them explicitly in the unload effect, so a repeated
        // update can never leak a 60s tick or a boot timeout.
        ctx.effect(() => {
            const boot = ctx.timer.timeout(() => {
                // Load the persisted config first, then run startup reconciliation.
                // Balance history loads in parallel (keyId-gated; independent of config).
                void loadConfig().then(() => {
                    if (cfg.reconcileOnStart) {
                        const r = reconcile();
                        if (r.restored > 0)
                            console.log('[save-money] startup reconcile restored ' + r.restored + ' goal(s)');
                    }
                });
                void loadBalanceHistory();
            }, 100);
            const tick = ctx.timer.interval(() => {
                try {
                    // Fallback release: whenever the gate is open (window ended / disabled /
                    // end-window active) wake the waiters — this MUST run before the enabled
                    // check, so disabling also releases waiters and suspended requests never
                    // hang forever.
                    if (!gateClosedAt(new Date()))
                        wakeGateWaiters();
                    if (!cfg.enabled)
                        return;
                    onTick(new Date());
                }
                catch (e) {
                    // A timer callback is a host callback: an escaping exception would be
                    // an uncaughtException and crash the harness. Log and continue.
                    console.error('[save-money] tick failed: ' + String((e && e.message) || e));
                }
            }, 60000);
            return () => {
                for (const dispose of [boot, tick]) {
                    try {
                        dispose();
                    }
                    catch (e) { /* unload must never throw */ }
                }
            };
        });
        // fs may activate AFTER the 100ms boot timer on compositions where the
        // save-money row precedes the base bundle's fs-sandbox row. Wait for the
        // service (Cordis resolves the dependency as soon as it exists) and run the
        // same boot load + reconcile then — loadConfig is idempotent (it re-reads
        // the file and re-applies), so running it a second time is harmless and
        // only fills the gap when the first attempt found no fs yet.
        if (typeof ctx.inject === 'function') {
            // Bind keeps `this` (the ctx) when Cordis calls the returned inject
            // function, and gives the closure a non-optional reference so the
            // strict-null check in the delayed callback is satisfied.
            const inject = ctx.inject.bind(ctx);
            ctx.effect(() => inject(['fs'], (sub) => {
                sub.effect(() => {
                    void loadConfig().then(() => {
                        if (cfg.reconcileOnStart) {
                            const r = reconcile();
                            if (r.restored > 0)
                                console.log('[save-money] late-fs reconcile restored ' + r.restored + ' goal(s)');
                        }
                    });
                });
            }));
        }
        // ---------- Status ----------
        function status(now) {
            const st = computeRawState(now);
            const col = collectTasks();
            const out = {
                enabled: cfg.enabled,
                state: st.name,
                reason: st.reason || null,
                gate: gateClosedAt(now) ? 'closed' : 'open',
                gateInstalled,
                // Diagnostics (runtime workspace resolution) — helps verify where the
                // config file is loaded from / persisted to. resolveWorkspaceRoot is
                // async (pointer + fs probes), so report the last resolved value.
                workspaceRoot: resolvedConfigDir || defaultWorkspaceRoot,
                configLoaded,
                configPath,
                nowUTC: now.toISOString(),
                nowLocal: String(now),
                busy: col.ok ? (col.tasks.length > 0) : null,
                activeGoals: col.ok ? col.tasks.filter((t) => t.phase === 'active').length : null,
            };
            // Balance staleness signal: true when a user message arrived since the
            // last balance query (the client refreshes on the next poll).
            out.balanceDirty = balanceDirty;
            if (st.window) {
                const tz = st.window.timezone || cfg.timezone;
                const wc = wallClock(tz, now);
                const pUTC = wallToUTC(tz, wc.y, wc.mo, wc.d, parseHHMM(st.window.pauseAt));
                const rUTC = wallToUTC(tz, wc.y, wc.mo, wc.d, parseHHMM(st.window.resumeAt));
                out.window = {
                    pauseAt: st.window.pauseAt,
                    resumeAt: st.window.resumeAt,
                    timezone: tz,
                    pauseUTC: new Date(pUTC).toISOString(),
                    resumeUTC: new Date(rUTC).toISOString(),
                };
            }
            if (st.name === 'WARN')
                out.minutesToPause = st.minutesToPause;
            if (endWindowUntil > now.getTime())
                out.endWindowUntil = new Date(endWindowUntil).toISOString();
            out.pauseRecord = pauseRecord ? {
                at: pauseRecord.at,
                window: pauseRecord.window,
                pausedCount: (pauseRecord.paused || []).length,
                paused: (pauseRecord.paused || []).map((p) => ({ sessionId: p.sessionId, goalId: p.goalId })),
            } : null;
            out.config = snapshot();
            return out;
        }
        // ---- Host RPC (dynamic-plugin form: registered on the harness sandbox)
        // ---- + HTTP endpoints (official bundle form ONLY: the bundled Client half
        //      talks to the same-origin webServer; the dynamic Client half keeps
        //      using the harness RPC below and never registers routes on the host's
        //      global webServer).
        const harnessApi = typeof harness !== 'undefined' ? harness : null;
        if (harnessApi) {
            ctx.effect(() => harnessApi.handle('save-money/status', async () => status(new Date())));
            ctx.effect(() => harnessApi.handle('save-money/configure', async (args) => applyConfig(unwrap(args) || {})));
        }
        const webServer = ctx.get('webServer');
        // The plugin row only injects timer, so in the official bundle form apply()
        // can run BEFORE the webServer service is registered. Register the HTTP
        // endpoints via Cordis' inject() dependency waiting — it runs the callback
        // as soon as webServer is available (immediately when already present), so
        // the bundled Client half never sees 404s (e.g. the Enable checkbox would
        // silently fail to configure). The disposer returned by webServer.register
        // is owned by the injected sub-context. Skipped entirely in the dynamic
        // form (harnessApi present).
        const registerHttpEndpoints = (ws) => {
            if (!ws || typeof ws.register !== 'function')
                return;
            const sendJson = (res, code, obj) => {
                res.writeHead(code, { 'content-type': 'application/json; charset=utf-8' });
                res.end(JSON.stringify(obj));
            };
            return ws.register({
                kind: 'prefix',
                path: '/save-money',
                handler: async (req, res) => {
                    try {
                        const rawPath = String(req.url || '/').split('?')[0];
                        const path = rawPath.length > 1 ? rawPath.replace(/\/+$/, '') : rawPath;
                        if (path === '/save-money/status') {
                            sendJson(res, 200, status(new Date()));
                            return;
                        }
                        if (path === '/save-money/balance') {
                            sendJson(res, 200, await balanceQuery());
                            return;
                        }
                        if (req.method === 'POST' && path === '/save-money/configure') {
                            let raw = '';
                            for await (const chunk of req)
                                raw += chunk;
                            let patch = {};
                            try {
                                patch = JSON.parse(raw || '{}');
                            }
                            catch (e) {
                                patch = {};
                            }
                            sendJson(res, 200, applyConfig(patch));
                            return;
                        }
                        if (req.method === 'POST' && path === '/save-money/end-window') {
                            for await (const _ of req) { /* drain */ }
                            sendJson(res, 200, await endWindowHandler());
                            return;
                        }
                        sendJson(res, 404, { ok: false, message: 'not found: ' + path });
                    }
                    catch (e) {
                        sendJson(res, 500, { ok: false, message: String((e && e.message) || e) });
                    }
                },
            });
        };
        if (!harnessApi && webServer && typeof webServer.register === 'function') {
            ctx.effect(() => registerHttpEndpoints(webServer));
        }
        else if (!harnessApi && typeof ctx.inject === 'function') {
            ctx.inject(['webServer'], (sub) => {
                sub.effect(() => registerHttpEndpoints(sub.get('webServer')));
            });
        }
        // UTC instant of a window's resumeAt (handles midnight-crossing windows).
        const endWindowUntilUTC = (w, tz, baseWc, dayOffset) => {
            const p = parseHHMM(w.pauseAt), r = parseHHMM(w.resumeAt);
            const off = dayOffset + (r < p ? 1 : 0);
            const base = new Date(Date.UTC(baseWc.y, baseWc.mo - 1, baseWc.d + off));
            return wallToUTC(tz, base.getUTCFullYear(), base.getUTCMonth() + 1, base.getUTCDate(), r);
        };
        // "End this save mode" — one-shot, current window only:
        //  - paused: immediately resumes frozen goals and clears the record
        //  - pause upcoming (WARN): cancels the upcoming pause
        //  - no active window: nothing happens (never touches later windows)
        // The window is skipped until its resumeAt; the next window (today or
        // later) still takes effect; the persistent `enabled` flag is untouched.
        const endWindowHandler = async () => {
            const now = new Date();
            const raw = computeRawState(now);
            if (!raw.window) {
                console.log('[save-money] end-window: no active window');
                return { ok: false, message: 'no active pause window to end', ...status(now) };
            }
            const tz = raw.window.timezone || cfg.timezone;
            const wc = wallClock(tz, now);
            endWindowUntil = endWindowUntilUTC(raw.window, tz, wc, 0);
            endWindowKey = windowKey(raw.window, tz);
            if (lastStateKey.split(':')[0] === 'PAUSED') {
                lastStateKey = 'NORMAL';
                unfreeze();
            }
            wakeGateWaiters(); // the gate is now open (endWindowUntil), release immediately
            console.log('[save-money] ended save mode for this window until ' + new Date(endWindowUntil).toISOString());
            return status(new Date());
        };
        if (harnessApi) {
            ctx.effect(() => harnessApi.handle('save-money/end-window', async () => endWindowHandler()));
        }
        // ---- Account balance (DeepSeek API /user/balance, shown in the header) ----
        // Implemented in src/balance-host.ts (inlined at build time): host-side
        // request, official-API guard, fetch/curl transport, 60s cache + in-flight
        // dedupe. The balance display is opt-in (cfg.showBalance, persisted,
        // default off): when off, the query reports unavailable so the UI hides
        // the balance entirely. Every failure returns ok:false and never throws.
        const balanceSvc = createBalanceService(ctx, { sandbox: !!harnessApi });
        // 余额历史(5 分钟采样 × 288 = 24 小时):由余额变化计算
        // 最近 1 小时 / 10 分钟 / 24 小时的消费金额。
        // 持久化到 ~/.dsh/dsh-save-money-balance.json(账户级、跨项目共享),
        // 插件更新/重启不丢历史;文件带 keyId 指纹,换 key(=换账户)自动作废旧历史。
        const balanceHistory = createBalanceHistory();
        const historyFile = (() => {
            const home = dshHome();
            return home ? home + (home.includes('\\') ? '\\' : '/') + BALANCE_HISTORY_FILE : '';
        })();
        // 本环境活动信号:llm/stream 每次请求都打点;采样点据此标记 activity,
        // 柱形图用它在「下降」时区分「本环境消费」(可信)与「可能外部消费」(警示)。
        let lastActivityAt = 0;
        let historyDirty = false;
        let historyKeyId = null;
        // 记录一次余额(带当前活动信号),并标脏待写盘。
        const recordBalance = (total) => {
            const now = Date.now();
            // 活动信号:距上次 llm/stream 请求在 SAMPLE_MS 内 → 本环境有活动
            const activity = lastActivityAt > 0 && now - lastActivityAt < SAMPLE_MS;
            balanceHistory.record(total, now, activity);
            historyDirty = true;
        };
        // 加载持久化历史:keyId 与当前凭据指纹一致才采用(否则旧账户轨迹作废)。
        const loadBalanceHistory = async () => {
            const fs = getFs();
            if (!fs || !historyFile)
                return;
            try {
                const text = await fs.readText(await fs.resolve(historyFile));
                const parsed = parseBalanceHistory(text);
                if (!parsed) {
                    console.log('[save-money] balance history: unreadable, starting fresh');
                    return;
                }
                const creds = ctx.get('credentials');
                const key = creds && typeof creds.resolve === 'function'
                    ? await creds.resolve('DEEPSEEK_API_KEY').then((r) => r && r.value).catch(() => undefined)
                    : undefined;
                historyKeyId = typeof key === 'string' && key.length > 0 ? keyFingerprint(key) : null;
                if (parsed.keyId !== historyKeyId) {
                    console.log('[save-money] balance history: key changed (' + String(parsed.keyId) + ' → ' + String(historyKeyId) + '), discarding old history');
                    balanceHistory.clear();
                    return;
                }
                balanceHistory.load(parsed.points);
                console.log('[save-money] balance history loaded: ' + balanceHistory.points().length + ' samples');
            }
            catch (e) {
                console.log('[save-money] balance history: none yet (fresh start)');
            }
        };
        // 写盘:best-effort,绝不 throw。
        const persistBalanceHistory = async () => {
            const fs = getFs();
            if (!fs || !historyFile)
                return;
            historyDirty = false;
            try {
                const creds = ctx.get('credentials');
                const key = creds && typeof creds.resolve === 'function'
                    ? await creds.resolve('DEEPSEEK_API_KEY').then((r) => r && r.value).catch(() => undefined)
                    : undefined;
                const kid = typeof key === 'string' && key.length > 0 ? keyFingerprint(key) : historyKeyId || 'unknown';
                historyKeyId = kid;
                const points = balanceHistory.points();
                const target = await fs.resolve(historyFile);
                // 写入位置:历史文件所在目录(~/.dsh)作为 workspaceRoot,确保沙箱放行。
                const dir = historyFile.slice(0, Math.max(historyFile.lastIndexOf('\\'), historyFile.lastIndexOf('/')));
                await fs.writeText(target, serializeBalanceHistory({ keyId: kid, points }), undefined, undefined, { mode: 'workspace-write', workspaceRoot: dir });
            }
            catch (e) {
                console.error('[save-money] balance history persist failed: ' + String((e && e.message) || e));
            }
        };
        // 卸载时强制落盘(异步尽力,通常能完成)。
        ctx.effect(() => {
            return () => {
                if (historyDirty)
                    void persistBalanceHistory();
            };
        });
        /** 拉一次余额并写入历史采样点(5 分钟窗口内只更新不新增)。 */
        const sampleBalance = async () => {
            try {
                const out = await balanceSvc.query();
                if (out && out.ok && Array.isArray(out.balance) && out.balance.length > 0 && typeof out.balance[0].total === 'string') {
                    const total = parseFloat(out.balance[0].total);
                    if (Number.isFinite(total))
                        recordBalance(total);
                }
            }
            catch (e) { /* the sampler must never throw */ }
        };
        // 后端 5 分钟采样定时器:仅「显示余额」开启时拉取并记录(关闭时跳过,不产生请求)。
        ctx.effect(() => {
            const dispose = ctx.timer.interval(() => {
                if (cfg.showBalance)
                    void sampleBalance();
            }, 300000);
            return () => {
                try {
                    dispose();
                }
                catch (e) { /* unload must never throw */ }
            };
        });
        // 写盘节流:与采样同频 5 分钟;有脏数据才写(减少磁盘 IO)。
        ctx.effect(() => {
            const dispose = ctx.timer.interval(() => {
                if (historyDirty)
                    void persistBalanceHistory();
            }, 300000);
            return () => {
                try {
                    dispose();
                }
                catch (e) { /* unload must never throw */ }
            };
        });
        const balanceQuery = async () => {
            if (!cfg.showBalance)
                return { ok: false, error: 'balance display is disabled' };
            const out = await balanceSvc.query();
            balanceDirty = false; // a fresh balance was just fetched for the client
            // 把本次余额记为最新采样点(窗口内去重),再附带消费统计。
            if (out && out.ok && Array.isArray(out.balance) && out.balance.length > 0 && typeof out.balance[0].total === 'string') {
                const total = parseFloat(out.balance[0].total);
                if (Number.isFinite(total))
                    recordBalance(total);
            }
            // 统一的窗口时钟基准:spend 三窗口与柱形图共享同一个「配置时区整 10 分钟」
            // 对齐时刻,这样 m10 与 bars[0] 指向同一段时间(hover 卡与柱形图对得上),
            // 且都落在配置时区的整数边界上(与官方后台按当地整点计费可比)。
            const nowMs = Date.now();
            const alignedNow = (cfg.timezone ? alignWallClock(cfg.timezone, nowMs, 10 * 60 * 1000) : undefined)
                ?? (nowMs - (nowMs % (10 * 60 * 1000)));
            const spendAt = {
                m10: alignedNow - 10 * 60 * 1000,
                h1: alignedNow - 60 * 60 * 1000,
                // h24 跨天,不做 HH:mm 范围标注(避免"昨天/今天"歧义)
            };
            return {
                ...out,
                // Provider of the most recent model request: null when no request has
                // been made yet (show the balance — the official account is queryable),
                // otherwise the client shows the balance only for 'deepseek-official'.
                provider: lastRequestProvider,
                spend: {
                    m10: balanceHistory.spend(10 * 60 * 1000, alignedNow),
                    h1: balanceHistory.spend(60 * 60 * 1000, alignedNow),
                    h24: balanceHistory.spend(24 * 60 * 60 * 1000, alignedNow),
                },
                // 各窗口的起始时刻(ms),hover 卡据此标注精确时间范围
                spendAt,
                // 最近 8 小时、10 分钟一根的消费柱形(第 0 根 = 最近 10 分钟);
                // 与 spend 相同来源、相同对齐基准,点击余额后由客户端绘制。
                bars: spendBars(balanceHistory.points(), nowMs, 48, 10 * 60 * 1000, cfg.timezone),
            };
        };
        if (harnessApi) {
            ctx.effect(() => harnessApi.handle('save-money/balance', async () => balanceQuery()));
        }
        // ---- Dynamic tools ----
        // Registered through harness in the dynamic-plugin sandbox; through the
        // ctx.tools service in the official module (plugin/index.js) form.
        const TOOL_DEFS = [
            {
                name: 'save_money_status',
                description: 'Query the save-money plugin state: enabled, gate state (NORMAL/WARN/PAUSED), busy detection, current window with UTC projection, PauseRecord summary, and full config.',
                parameters: { type: 'object', properties: {} },
                execute: async () => status(new Date()),
            },
            {
                name: 'save_money_configure',
                description: 'Set the save-money plugin configuration. Partial patch: enabled (bool), timezone (IANA name), warnMinutes (number), reconcileOnStart (bool), lang (auto/zh/zh-TW/en/de/fr/es/it/pt/ja/ko), showBalance (bool, shows the DeepSeek account balance in the header; off by default), modelApply (object of booleans: official-flash / official-pro / opencode-flash / opencode-pro — checked = pause this model tier inside windows, unchecked = exempt), windows (array of {pauseAt, resumeAt, days?, timezone?}, HH:mm wall-clock in the window timezone). Validates, stores in memory, and persists to the workspace config file. Returns the applied config.',
                parameters: {
                    type: 'object',
                    properties: {
                        enabled: { type: 'boolean' },
                        timezone: { type: 'string' },
                        warnMinutes: { type: 'number' },
                        reconcileOnStart: { type: 'boolean' },
                        lang: { type: 'string' },
                        showBalance: { type: 'boolean' },
                        modelApply: {
                            type: 'object',
                            properties: {
                                'official-flash': { type: 'boolean' },
                                'official-pro': { type: 'boolean' },
                                'opencode-flash': { type: 'boolean' },
                                'opencode-pro': { type: 'boolean' },
                            },
                        },
                        windows: {
                            type: 'array',
                            items: {
                                type: 'object',
                                properties: {
                                    pauseAt: { type: 'string' },
                                    resumeAt: { type: 'string' },
                                    days: { type: 'array', items: { type: 'number' } },
                                    timezone: { type: 'string' },
                                },
                            },
                        },
                    },
                },
                execute: async (args) => applyConfig(unwrap(args) || {}),
            },
            {
                name: 'save_money_end_window',
                description: 'End save mode for the currently active pause window only (one-shot, in-memory, not persisted): if paused, immediately resumes frozen goals and releases the request gate; if a pause is upcoming, cancels it. The window is skipped until its resumeAt. The next window (today or later) still takes effect; the persistent enabled flag is untouched. Returns the new status.',
                parameters: { type: 'object', properties: {} },
                execute: async () => endWindowHandler(),
            },
            {
                name: 'save_money_debug_tick',
                description: 'Development tool: run one state-machine transition manually (as if a tick fired now). Returns the new status. Useful to verify freeze/resume without waiting for the timer.',
                parameters: { type: 'object', properties: {} },
                execute: async () => {
                    onTick(new Date());
                    return status(new Date());
                },
            },
        ];
        for (const def of TOOL_DEFS) {
            const tool = {
                ...def,
                output: {
                    schema: { type: 'object', properties: {}, additionalProperties: true },
                    render: (_args, result) => [{ type: 'text', text: JSON.stringify(result) }],
                },
            };
            if (harnessApi) {
                ctx.effect(() => harnessApi.registerTool(ctx, harnessApi.defineTool(tool)));
            }
            else {
                const tools = ctx.get('tools');
                if (tools && typeof tools.register === 'function')
                    ctx.effect(() => tools.register(tool));
            }
        }
    }
