/**
 * make-plugin.js — Generate the official DSH plugin bundle from the built
 * Host and Client bodies.
 *
 * Converts the dynamic-plugin bodies (dist/host.js, dist/client.js — each a
 * top-level `return { inject, apply(ctx) {...} }` produced by scripts/build.js
 * from src/host.ts / src/client.ts) into the DeepSeek Harness official plugin
 * module:
 *
 *   - plugin/index.js  — Host half: `export const name / inject / apply(ctx)`
 *   - plugin/client.js — Client half: the browser bundle format consumed by
 *     `window.__ModuleLoader__.load({ id, factory })` (client-modules), with
 *     React resolved through the module table (`require('react')`).
 *
 * It also updates plugin/package.json so the bundle declares the browser half:
 * `exports["./client"]` + `dsh.client: { platform: "web" }` — client-modules
 * discovers the declaration, serves the bundle at /plugins/<id>/client.js and
 * the browser mounts the UI automatically. No dynamic-plugin step needed.
 *
 * Usage: node scripts/make-plugin.js   (writes plugin/index.js, plugin/client.js,
 *                                       plugin/package.json)
 *
 * Official install paths (see README "Install"):
 *   1. Quick try:  `dsh web --patch ./cordis.patch.yml` (loads the local file)
 *   2. Formal:     pack a bundle → `dsh plugin --profile web add ./dsh-save-money`
 *
 * Note: both halves are now bundled. The Host half carries scheduling / gate /
 * freeze / tools / HTTP endpoints; the Client half (status text / banner /
 * settings page) is auto-discovered from the package's dsh.client declaration.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// ---------- Host half: plugin/index.js ----------
const src = readFileSync(join(root, 'dist', 'host.js'), 'utf8')

// Dynamic-plugin body: core helpers (inlined) + `return { inject: ['timer'],
// apply(ctx) { ... } }` → standard module: core helpers stay top-level,
// `export function apply(ctx) { ... }`.
let body = src
  .replace(/^\/\*\*[\s\S]*?\*\/\s*/, '') // drop the dynamic-plugin header comment (the generated file carries its own)
  .replace(/\nreturn \{\s*\n\s*inject: \['timer'\],\s*\n\s*apply\(ctx\) \{/, '\nexport function apply(ctx) {')
  .trimEnd()

// The original object literal tail `    },\n};` (apply close + object close +
// comma + semicolon, at any indent) → function body tail `    }`
body = body.replace(/\n(\s*)\},\n\};\s*$/, '\n$1}')

if (body.includes('export function apply(ctx)') === false) {
  throw new Error('conversion failed: apply(ctx) wrapper not found in dist/host.js')
}

const hostOut = `/**
 * dsh-save-money — Host half (official plugin module, generated by
 * scripts/make-plugin.js from dist/host.js, built from src/host.ts).
 *
 * Deployment form: DeepSeek Harness official bundle / --patch mount (see
 * README "Install"). Behaviour is identical to the dynamic-plugin form:
 * time-window scheduling + goal freeze/resume + PauseRecord + llm/stream
 * request-level gate (event-driven suspension) + dynamic tools + HTTP
 * endpoints (/save-money/*) for the bundled Client half + config persistence.
 */

export const name = 'dsh-save-money'
export const inject = ['timer']

${body}
`
writeFileSync(join(root, 'plugin', 'index.js'), hostOut)
console.log('[make-plugin] wrote plugin/index.js')

// ---------- Client half: plugin/client.js ----------
const clientSrc = readFileSync(join(root, 'dist', 'client.js'), 'utf8')
const clientBody = clientSrc
  .replace(/^\/\*\*[\s\S]*?\*\/\s*/, '') // drop the dynamic-plugin header comment
  .trimEnd()

// The browser bundle is a factory registered with window.__ModuleLoader__
// (client-modules contract): factory(require) → module.exports = { apply, inject }.
// The plugin body (core helpers + `return { inject, apply }`) runs inside an
// IIFE; React is resolved through the module table, and the host `globalThis`
// `host` builtin (dynamic form) is absent here, so callHost() falls back to
// the same-origin /save-money/* HTTP endpoints.
const clientOut = `/**
 * dsh-save-money — Client half (official browser bundle, generated by
 * scripts/make-plugin.js from dist/client.js, built from src/client.ts).
 *
 * Loaded automatically by the Web shell: plugin/package.json declares
 * dsh.client + exports["./client"], client-modules serves this file at
 * /plugins/dsh-save-money/client.js and the browser mounts it on startup —
 * no dynamic-plugin step or approval needed.
 */

window.__ModuleLoader__.load({
  id: 'dsh-save-money',
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    const React = require('react');
    var plugin = (() => {
${clientBody}
    })();
    exports.apply = plugin.apply;
    exports.inject = plugin.inject;
    return module.exports;
  }
});
`
writeFileSync(join(root, 'plugin', 'client.js'), clientOut)
console.log('[make-plugin] wrote plugin/client.js')

// ---------- plugin/package.json: declare the browser half ----------
const pkgPath = join(root, 'plugin', 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
pkg.exports = {
  '.': './index.js',
  './client': './client.js',
  './package.json': './package.json',
}
pkg.dsh = {
  bundle: { patch: './cordis.patch.yml' },
  client: { platform: 'web' },
}
if (!pkg.files || pkg.files.indexOf('client.js') < 0) {
  pkg.files = [...(pkg.files || []), 'client.js']
}
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
console.log('[make-plugin] updated plugin/package.json (exports["./client"] + dsh.client)')
