/**
 * make-plugin.js — Generate the official DSH plugin module from the built
 * Host body.
 *
 * Converts the dynamic-plugin body (dist/host.js, a top-level
 * `return { inject, apply(ctx) {...} }` produced by scripts/build.js from
 * src/host.ts) into the DeepSeek Harness official ESM plugin module:
 *   export const name / export const inject / export function apply(ctx)
 *
 * Usage: node scripts/make-plugin.js   (writes plugin/index.js)
 *
 * Official install paths (see README "Install"):
 *   1. Quick try:  `dsh web --patch ./cordis.patch.yml` (loads the local file)
 *   2. Formal:     pack a bundle → `dsh plugin --profile web add ./dsh-save-money`
 *
 * Note: all Host logic (scheduling / gate / freeze / tools / RPC) lives in the
 * Host half, so the bundle is fully functional. The Client UI (status text /
 * banner / settings page) currently ships through the dynamic-plugin form;
 * bundling the Client half is future work.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = readFileSync(join(root, 'dist', 'host.js'), 'utf8')

// Dynamic-plugin body: core helpers (inlined) + `return { inject: ['timer'],
// apply(ctx) { ... } }` → standard module: core helpers stay top-level,
// `export function apply(ctx) { ... }`.
let body = src
  .replace(/^\/\*\*[\s\S]*?\*\/\s*/, '') // drop the dynamic-plugin header comment (the generated file carries its own)
  .replace(/\nreturn \{\s*\n\s*inject: \['timer'\],\s*\n\s*apply\(ctx\) \{/, '\nexport function apply(ctx) {')
  .trimEnd()

// The original object literal tail `    },\n};` (apply close + object close +
// comma + semicolon, at any indent) → function body tail `    }`
body = body.replace(/\n(\s*)\},\n\};\s*$/, '\n$1}')

if (body.includes('export function apply(ctx)') === false) {
  throw new Error('conversion failed: apply(ctx) wrapper not found in dist/host.js')
}

const out = `/**
 * dsh-save-money — Host half (official plugin module, generated by
 * scripts/make-plugin.js from dist/host.js, built from src/host.ts).
 *
 * Deployment form: DeepSeek Harness official bundle / --patch mount (see
 * README "Install"). Behaviour is identical to the dynamic-plugin form:
 * time-window scheduling + goal freeze/resume + PauseRecord + llm/stream
 * request-level gate (event-driven suspension) + dynamic tools + RPC +
 * config persistence. Host half only; the Client UI (status text / banner /
 * settings page) ships through the dynamic-plugin form.
 */

export const name = 'dsh-save-money'
export const inject = ['timer']

${body}
`
writeFileSync(join(root, 'plugin', 'index.js'), out)
console.log('[make-plugin] wrote plugin/index.js')
